### ISSUE TITLE
Starting px after install

### ISSUE THREAD

**Issue by MarcJefferson5** [genotrance/px#101]
Hi, 

px doesn't start on its own after px --install. It just adds px to windows autostart. Please change it, so that it starts on its own as GUI after install or add an option to do that. 

And Is there a way to manually start px as GUI using cmd or powershell? Whenever I try that is starts as console application.

**Comment by thokuest** [comment]
I hope that answers your question:

> Px doesn't have any GUI and runs completely in the background.

-- [Readme](https://github.com/genotrance/px#dependencies)

**Comment by ponchofiesta** [comment]
Maybe this issue should be called **[Fearure Request] GUI**
But as px2 has started, the author may never add this. (And IMHO it isn't need)
