### ISSUE TITLE
Calling px.exe is Blocking the Command Line

### ISSUE THREAD

**Issue by JAAdrian** [genotrance/px#103]
Hey all and thanks for this great software! It has solved countless issues behind our company proxy server.

My question at hand is regarding an issue I am currently facing trying to start `px` from the command line. I'd like to include a call to start `px` in some form of script (let's assume a Windows cmd file) and pass some additional infos of what credentials to use. I assume a Jenkins environment which runs as a Windows service and I cannot guarantee that a person with well-setup `px` is logged into the machine at all times.

When I call `px` from the command line, it will kind of block and only returns when hitting enter once. When I call it from a cmd script, it will just block the script's execution. I tried `start` and `call` without any luck

```batch
start px.exe
echo I'm done!
```

I can see the successful start of the `px` service but the script does not continue to print the echo line.

Does anyone have some recommendations here? Do I need to send a carriage return via the script?

Using `px` version 0.4.0 from the release page.

**Comment by boerngen-schmidt** [comment]
@JAAdrian I do not have a fix for it, but if you plan to run the Proxy on Startup, you can create a Shortcut in Startup [see Microsoft Docs](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd)

There you can create a new shortcut pointing to px.exe and Windows will automatically launch px upon login. The easiest way to terminate px then is via task manager or run ``taskkill /IM "px.exe" /F``

**Comment by genotrance** [comment]
This is how I was testing px - might give some ideas.

https://github.com/genotrance/px/blob/master/test.py#L142

**Comment by monti-python** [comment]
Hi @JAAdrian, I was also having this issue, the problem is that the workers attach and dettach the console when initializing, so it's not possible to just pipe `echo.` to `px.exe` as expected...

I was able to workaround it by calling the binary asyncronously with `start /b cmd /c px.exe`. If you need px to be running before continuing the script you could block the execution until the port is open (using `netstat` in a while-like loop for example)

Hope it helps!

**Comment by JAAdrian** [comment]
Hi all and thanks for your comments and solutions! 
I will sure give your solutions, @genotrance  and @monti-python, a try. Those should actually do what I am looking for.
