### ISSUE TITLE
Sharepoint NTLM

### ISSUE THREAD

**Issue by yapnel** [genotrance/px#105]
My use case is to use px as a standalone forward proxy server to authenticate against SharePoint's NTLM using NOPROXY. 

I am wondering if this is possible please? 

Please advise

Thanks

**Comment by genotrance** [comment]
Px does not support this - is only proxy auth that's supported today.

Px2 can support this easily since it uses libcurl as the backend. It is still under dev though. 

https://github.com/genotrance/px2
