### ISSUE TITLE
Px.exe blocked by McAfee

### ISSUE THREAD

**Issue by braykov** [genotrance/px#106]
This is most probably a false threat, but it still is a showstopper as it does not allow me to install Px.
When I try to run the bundled Px.exe windows tells me "The system cannot execute the specified program." because McAfee blocks it with this message: 

> Adaptive Threat Protection blocked access because the reputation (Most Likely Malicious) is below the configured Block threshold.

Threat Name:

> JTI/Suspect.65770!6e8e843f1a7c

**Comment by GregoryOtt** [comment]
[VirusTotal](https://www.virustotal.com/gui/home/upload) reports that 3/72 block px.exe

**Comment by Klaas-** [comment]
This seems to happen often, talk to your antivirus vendors. #23 #62 #78 #92

**Comment by genotrance** [comment]
Binary releases have been problematic and efforts on px has been minimal so releases are lagging and infrequent.

I'm moving towards a source only release model so this won't be fixed or relevant going forward.

**Comment by genotrance** [comment]
Note that binary builds are back - see https://github.com/genotrance/px/issues/130#issuecomment-1075307879. It is now built with Nuitka so hopefully we see fewer such issues.
