### ISSUE TITLE
Add a little more documentation

### ISSUE THREAD

**Issue by holgerreif** [genotrance/px#11]
I propose as background information to add a link to https://msdn.microsoft.com/en-us/library/dd925287.aspx which explains the sequence of the NTLM authentication.

Furthermore you should mention (e.g. as an ini file comment), that the log files are written in to the directory where px got started and that previous logs get overwritten at every start of the tool.

Otherwise thanks fot the cool piece of Software!

**Comment by genotrance** [comment]
Thanks for the feedback, I'll make these changes.

**Comment by genotrance** [comment]
I've added both changes to the repo, I'll mark this closed when I post a newer ZIP.

**Comment by genotrance** [comment]
Just posted v0.3.0 so marking this as closed.
