### ISSUE TITLE
KERBEROS Authentication failing (and falling back on NTLM) for proxy servers  

### ISSUE THREAD

**Issue by k0l0nell** [genotrance/px#110]
When the proxy server host name is referring to a Alias record (or CNAME record) Kerberos Authentication will fail as tickets can't be issued (SPN does not exist)

**Comment by k0l0nell** [comment]
Raised PR #111

**Comment by genotrance** [comment]
Closing this since we are now relying on libcurl to do the auth. If it recurs with v0.7.0+, we will have to re-evaluate.
