### ISSUE TITLE
Feature Request: Add Basic Auth to protect px itself

### ISSUE THREAD

**Issue by bjonen** [genotrance/px#117]
It would be nice to allow basic proxy authentication for cases when it is necessary to expose the proxy on the network (0.0.0.0). 

curl -v -x username:password@<network_ip>:3128 https://www.google.com

**Comment by genotrance** [comment]
What login:pass would we use for this? The same as the upstream proxy? Or a separate pair altogether? Or maybe support both?

What auth type - basic/digest? Or some custom token based? What will make it most accessible?

I'd like to add that Px already has decent IP based filtering for clients that can be leveraged for now.

**Comment by genotrance** [comment]
This is supported in v0.9.0 coming out soon - see [branch](https://github.com/genotrance/px/tree/v090).

NEGOTIATE, NTLM, DIGEST and BASIC auth are all supported with SSPI when available.

**Comment by genotrance** [comment]
[v0.9.0](https://github.com/genotrance/px/releases/tag/v0.9.0) has been released finally!
