### ISSUE TITLE
Websockets & Idle Timeout

### ISSUE THREAD

**Issue by btsimonh** [genotrance/px#121]
Just a note for anyone else who is using PX and websockets.

The default idle timeout may not be most appropriate of you are running websockets through px....
I was using px to test proxying from nodejs, and my websocket connection was getting disconnected every 30s because px was detecting idle on the connection.

Having set --idle=120, the websocket remains open (longer than 2 minutes.).

I'm running MQTT over the websocket, and I believe the default MQTT keepalive period is probably 60s -so it will depend on what you are running over the websocket...

The good news is that px happily tunnels wss as long as you keep it active :).

thanks again for a nice project.

**Comment by genotrance** [comment]
Thank you for testing and sharing this.
