### ISSUE TITLE
Requires module pywin32

### ISSUE THREAD

**Issue by gabriead** [genotrance/px#126]
Dear px developers,

I have installed px via pip (pip install px-proxy). When I try to configure it 'px --proxy' it asks for pywin32.
Although I have installed it (see screenshot). What might causes this?
OS: Win 10 , python Version=3.9
<img width="184" alt="proxy" src="https://user-images.githubusercontent.com/9105222/150991505-b2aba267-e316-4d09-b286-3bd4387422f2.PNG">

**Comment by genotrance** [comment]
I believe this was fixed in #122 so please clone from Github. The version of px in pip is old.

**Comment by gabriead** [comment]
Same error occurs with the cloned version

**Comment by genotrance** [comment]
I just tried this and don't see the issue. How are you running px? Can you please share the command line and output with `--debug`?

**Comment by genotrance** [comment]
Closing this and will track with #129.
