### ISSUE TITLE
Requires module pywin32 sspi

### ISSUE THREAD

**Issue by Cpousson** [genotrance/px#129]
Running on python 3.9.
install complete with winpy32 and sspi.py file in supporting Programs\Python\Python39-32\Lib\site-packages folder but running python -m px comes back with requires module pywin32 sspi. Not sure what is missing.

**Comment by Cpousson** [comment]
@tmallikarjuna, I never received support so I had to move on to a different solution. Good luck finding the help you need!

**Comment by genotrance** [comment]
I could not reproduce this issue last time I tried. Do you think it's because you have a 32-bit version of Python and maybe a 64-bit version of pywin32?

Will help to know how you installed Python and pywin32.
