### ISSUE TITLE
px.ini in release v0.5.1 and default settings

### ISSUE THREAD

**Issue by MrFly72** [genotrance/px#133]
Hi.

First of all, thank you for listening and bringing the .exe back, really great!

I am wondering if px could act the same way with px.ini that it does without px.ini present.
So basically:
If Server + PAC values are empty in the px.ini, react the same way as if the px.ini would not be present by using Windows-User-Proxy Setting (IE-Settings or however we call it).
That would also come handy, for a lot of situations.

**Comment by genotrance** [comment]
I believe that's how it works - if there's anything in the ini file, it loads it, else it default initializes the settings as blank and then tries to load from system proxies.

**Comment by MrFly72** [comment]
Thats weird, as I wouldnt have mentioned it, if it worked in our environment.
With the default px.ini, it does not work, renaming it to px_disabled.ini it works.
Did not edit the px.ini at all.

**Comment by genotrance** [comment]
Can you please let me know how your proxy is setup in IE settings?

**Comment by MrFly72** [comment]
I am testing it just now on a test machine, hold on

**Comment by MrFly72** [comment]
@genotrance Sorry for the confusion, please close this, it is working now. I will do some more testing and then document the way for our VDI users.
