### ISSUE TITLE
px uses high CPU and ends in timeouts

### ISSUE THREAD

**Issue by moritzrupp** [genotrance/px#144]
Hi,

since upgrading to version 0.6.3, I have issues with px-proxy.
Directly after starting up, it works fine. Once it ran a little bit of time, it constantly consumes around 25% CPU and I only receive timeouts, no communication is possible anymore.

```
Proxy CONNECT aborted due to timeout
```

Log output:
```
PS> px --foreground=1 --debug=1 --uniqlog
Serving at 127.0.0.1:3128 proc MainProcess
```

Nothing more is printed.

px.ini:
```
[proxy]
server = xx.xx.xx.xx:xxxx,xx.xx.xx.xx:xxxx
pac =
listen = 127.0.0.1
port = 3128

gateway = 0

hostonly = 0

allow = *.*.*.*

noproxy = 127.0.0.1,10.0.0.0/8,192.168.0.0/16

useragent =

username =

auth =

[settings]
workers = 2
threads = 5
idle = 30
socktimeout = 20.0
proxyreload = 60
foreground = 0
log = 0
```

Any help is highly appreciated. :)

Thanks in advance
Moritz

**Comment by genotrance** [comment]
Please run with `—debug`. It should print out the logs and give an idea what the issue is.

**Comment by genotrance** [comment]
Please reopen if any updates.

**Comment by moritzrupp** [comment]
Hi @genotrance,

sorry for the late response. The issue stopped occuring after upgrading to 0.7.0.

Thanks and best regards
Moritz
