### ISSUE TITLE
px --install doesn't use full path

### ISSUE THREAD

**Issue by drguildo** [genotrance/px#146]
When doing `px --install` to run px at startup, the registry entry it creates doesn't contain the full path to the px executable, so if the directory it's located in isn't in the system or user path, px will fail to run.

```
>reg query HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /v Px

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    Px    REG_EXPAND_SZ    px.exe
```

**Comment by drguildo** [comment]
Thanks. It's a version 0.6.3 binary from the releases page.

**Comment by genotrance** [comment]
Workaround for now is to `--install` in powershell. I was able to reproduce the issue in cmd.
