### ISSUE TITLE
WSL v2 compatibility?

### ISSUE THREAD

**Issue by ensingerphilipp** [genotrance/px#149]
Hi there!

Im currently using px-proxy in WIndows and it works well!
I do have one Problem tho --> im not able to get it to work with WSLv2

Im Using Ubuntu2004 in WSL v2 and trying to connect to the px-proxy installation that is running on the Windows Host.

Anyone has an idea on how to do that?

**Comment by eitsupi** [comment]
Unlike WSL1, which is accessible via `localhost`, WSL2 does not have a special hostname to access a Windows address, so it is necessary to obtain a Windows IP address by some means. (Please check microsoft/WSL#4619)

Also remember that WSL2 is a VM, so you must specify `hostonly = 1` in the px settings.
https://github.com/genotrance/px#usage

**Comment by kusalk** [comment]
I haven't used this application in a while, but if I'm remembering correctly, I ran it as follows:
`./px.exe  --hostonly --gateway --allow=172.*.*.* --save --install`

Then added the following to `/etc/profile` in WSL2:
```
export http_proxy="http://$(tail -1 /etc/resolv.conf | cut -d' ' -f2):3128"
export https_proxy="http://$(tail -1 /etc/resolv.conf | cut -d' ' -f2):3128"
```
