### ISSUE TITLE
Not recognizing netaddr

### ISSUE THREAD

**Issue by 82dsoldier** [genotrance/px#15]
I have installed netaddr 0.7.19 per directions, but whenever I try to run px.py, I get the message "Requires modules netaddr".  I am running python 27 on Windows 7.

**Comment by genotrance** [comment]
Px checks for netaddr with a simple try/except block:-

```python
try:
    import netaddr
except:
    print("Requires modules netaddr")
    sys.exit()
```

Can you change that to just ```import netaddr``` and share the stack trace? Another alternative would be to run Python and type ```import netaddr``` on the prompt to see if it loads as expected.

**Comment by 82dsoldier** [comment]
If I comment out the try/except, I get this error message:

Traceback (most recent call last):
  File "px.py", line 69, in <module>
    NOPROXY = netaddr.IPSet([])
NameError: name 'netaddr' is not defined

However, if I run python and type import netaddr, I get no messages at all.  I assume that is expected behavior?  I'm not a python programmer.

**Comment by genotrance** [comment]
Makes no sense - how are you running Px? Can you please share the command line? And also the version of Python with the -V flag?
