### ISSUE TITLE
Successfully created EXE file is not executable.

### ISSUE THREAD

**Issue by Dan-the-Van** [genotrance/px#150]
Hi,

I was able to create a px.exe file based on v0.7.0 via pyinstaller. The below output indicates a successfull creation. 
However, the created exe file is not executable. 

Any help is highly appreciated.

          (px) PS C:\Users\q548601\projects\px_dev\px> python tools.py --pyinst
          864 INFO: PyInstaller: 4.8
          865 INFO: Python: 3.10.4 (conda)
          903 INFO: Platform: Windows-10-10.0.18363-SP0
          905 INFO: wrote C:\Users\q548601\projects\px_dev\px\px.spec
          909 INFO: UPX is not available.
          911 INFO: Removing temporary files and cleaning cache in C:\Users\q548601\AppData\Local\pyinstaller
          991 INFO: Extending PYTHONPATH with paths
          ['C:\\Users\\q548601\\projects\\px_dev\\px']
          1570 INFO: checking Analysis
          1573 INFO: Building Analysis because Analysis-00.toc is non existent
          1573 INFO: Initializing module dependency graph...
          1579 INFO: Caching module graph hooks...
          1580 INFO: Analyzing base_library.zip ...
          8149 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
          8151 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib'
          10489 INFO: Caching module dependency graph...
          10782 INFO: running Analysis Analysis-00.toc
          10791 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
            required by C:\Users\q548601\Miniconda3\envs\px\python.exe
          11224 INFO: Analyzing C:\Users\q548601\projects\px_dev\px\px.py
          13252 INFO: Analyzing hidden import 'win32timezone'
          13283 INFO: Processing module hooks...
          13283 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          13289 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          13289 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          13291 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          13453 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          13465 INFO: Loading module hook 'hook-importlib_metadata.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          13470 INFO: Loading module hook 'hook-keyring.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          13982 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          14103 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          14118 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          14121 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          14127 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          14545 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          14553 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          14556 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks'...
          15007 INFO: checking Tree
          15008 INFO: Building Tree because Tree-00.toc is non existent
          15010 INFO: Building Tree Tree-00.toc
          15189 INFO: checking Tree
          15190 INFO: Building Tree because Tree-01.toc is non existent
          15192 INFO: Building Tree Tree-01.toc
          15435 INFO: checking Tree
          15439 INFO: Building Tree because Tree-02.toc is non existent
          15440 INFO: Building Tree Tree-02.toc
          15513 INFO: Looking for ctypes DLLs
          15587 INFO: Analyzing run-time hooks ...
          15599 INFO: Including run-time hook 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
          15604 INFO: Including run-time hook 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
          15609 INFO: Including run-time hook 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
          15613 INFO: Including run-time hook 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
          15623 INFO: Including run-time hook 'C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
          15643 INFO: Looking for dynamic libraries
          16050 INFO: Looking for eggs
          16050 INFO: Using Python library C:\Users\q548601\Miniconda3\envs\px\python310.dll
          16057 INFO: Found binding redirects:
          []
          16072 INFO: Warnings written to C:\Users\q548601\projects\px_dev\px\build\px\warn-px.txt
          16193 INFO: Graph cross-reference written to C:\Users\q548601\projects\px_dev\px\build\px\xref-px.html
          16227 INFO: checking PYZ
          16229 INFO: Building PYZ because PYZ-00.toc is non existent
          16230 INFO: Building PYZ (ZlibArchive) C:\Users\q548601\projects\px_dev\px\build\px\PYZ-00.pyz
          17162 INFO: Building PYZ (ZlibArchive) C:\Users\q548601\projects\px_dev\px\build\px\PYZ-00.pyz completed successfully.
          17197 INFO: checking PKG
          17198 INFO: Building PKG because PKG-00.toc is non existent
          17199 INFO: Building PKG (CArchive) px.pkg
          20296 INFO: Building PKG (CArchive) px.pkg completed successfully.
          20306 INFO: Bootloader C:\Users\q548601\Miniconda3\envs\px\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
          20306 INFO: checking EXE
          20307 INFO: Building EXE because EXE-00.toc is non existent
          20308 INFO: Building EXE from EXE-00.toc
          20310 INFO: Copying bootloader EXE to C:\Users\q548601\projects\px_dev\px\dist\px.exe
          20328 INFO: Copying icon to EXE
          20328 INFO: Copying icons from ['C:\\Users\\q548601\\Miniconda3\\envs\\px\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-windowed.ico']
          20331 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
          20332 INFO: Writing RT_ICON 1 resource with 3752 bytes
          20333 INFO: Writing RT_ICON 2 resource with 2216 bytes
          20336 INFO: Writing RT_ICON 3 resource with 1384 bytes
          20342 INFO: Writing RT_ICON 4 resource with 38188 bytes
          20343 INFO: Writing RT_ICON 5 resource with 9640 bytes
          20344 INFO: Writing RT_ICON 6 resource with 4264 bytes
          20345 INFO: Writing RT_ICON 7 resource with 1128 bytes
          20360 INFO: Copying 0 resources to EXE
          20361 INFO: Emedding manifest in EXE
          20364 INFO: Updating manifest in C:\Users\q548601\projects\px_dev\px\dist\px.exe
          20365 INFO: Updating resource type 24 name 1 language 0
          20381 INFO: Appending PKG archive to EXE
          23913 INFO: Building EXE from EXE-00.toc completed successfully.

**Comment by genotrance** [comment]
I've moved onto Nuitka to create binaries for Px, not had any luck with PyInstaller in a while since binaries were being flagged by virus scanners. I'm actively removing remaining references to PyInstaller.

Can you try with Nuitka?

**Comment by genotrance** [comment]
It is basically two steps - first is to [download](https://github.com/genotrance/px/blob/master/tools.py#L140) the latest libcurl binaries:

```
python tools.py --libcurl
```

Next, you can [build](https://github.com/genotrance/px/blob/master/tools.py#L202) the Nuitka binaries as follows:

```
python tools.py --nuitka
```
