### ISSUE TITLE
PAC file encoding

### ISSUE THREAD

**Issue by SamuelePilleri** [genotrance/px#167]
My company uses IIS to distribute PAC configuration and the file has Windows-1251 encoding, causing this line to fail.

https://github.com/genotrance/px/blob/faaa57c2e7bd06f1bc502e8a1d63b6911a667c27/px/mcurl.py#L468

Changing it to `.decode("cp1251")` fixes it, but it may cause problems to other people. How can we approach this? Maybe with a dedicated entry on the configuration file? Or maybe trying with UTF-8 and then falling back to Windows-1251 in case of an exception?

Further discussion is needed.

**Comment by genotrance** [comment]
This is easy but hard - while `get_data()` is only used by Px to get PAC data, mcurl.py is generic and could be used by anyone as a standalone library. It is used in tools.py, for example, to download the curl DLL and to talk to Github. This suggests it should just return bytes and the caller should determine what encoding it should use.

However, it just delegates the headache to the caller who might have no clue what to do. At least, I don't know what's the recommended order of decoding bytes in pac.py. In this case, we know you can try `utf-8` and then `cp1251` but what about the other encodings? Is there a recommended order to attempt decoding or some way to figure out which decoding to use depending on the data?

**Comment by SamuelePilleri** [comment]
Sorry for the delay.

Ideally HTTP response headers should indicate the charset encoding along with the content type (something like `Content-Type: text/html;charset=utf-8`), but this is a never ending problem... StackOverflow suggests [charset-normalizer](https://pypi.org/project/charset-normalizer/) to automatically detect encoding, but this may be overkill...

My proposal: there are only 2 references to this function one in pac.py and one in tools.py. A viable way could be, as you suggested, move the problem one level up and:
* in tools.py just assume utf-8 by default since the software mostly queries Github and other web services that likely use UTF-8
* in pac.py assume utf-8 unless otherwise specified in px.ini file (adding a dedicated option)

What do you think?

**Comment by genotrance** [comment]
Are you able to test and see what your PAC file server returns for Content-Type? If you can run Px is debug mode, it should print out the headers for the PAC file request. Ideally, we can assume utf-8 for the headers and then use the headers to decide what charset to use for the body.

**Comment by SamuelePilleri** [comment]
Unfortunately that's not an option for me:

```
HTTP/1.1 200 OK
Content-Type: text/plain
Last-Modified: Mon, 28 Nov 2022 19:03:03 GMT
Accept-Ranges: bytes
ETag: "114fb8a5c3d91:0"
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Tue, 13 Dec 2022 09:49:48 GMT
Content-Length: 16731
```

**Comment by genotrance** [comment]
Reading [this link](https://www.w3.org/Protocols/rfc1341/7_1_Text.html) suggests that means it is `us-ascii`. Will you be able to test if your PAC file can be decoded with `decode("us-ascii")`? 

I'll need to update the code to default to `us-ascii` if there's no charset, else to use what the server sends back. Assuming `utf-8` does not seem to be the right way. Will need to check other areas of the code as well where I'm just forcing `utf-8`.

**Comment by SamuelePilleri** [comment]
Unfortunately, it doesn't. The character under examination here is `0xE8` which is `è` in Latin alphabets. My guess is that said file has been manually edited and uploaded on the server which is now failing to transmit its encoding along with the headers.

Also, I don't think you should change the encoding globally to US-ASCII since, as far as I remember, UTF-8 should be a backwards-compatible superset of US-ASCII.

**Comment by SamuelePilleri** [comment]
Also, I should point out that, while the file decodes correctly with Windows-1251 (Cyrillic, `cp1251`) as stated at the beginning of the issue, its much more likely that it has been authored with Windows-1252 (Latin, `cp1252`).

[charset-normalizer](https://pypi.org/project/charset-normalizer/) is starting to make sense in such a mess 🥲

**Comment by genotrance** [comment]
Wow that makes it harder to figure out. 

I'm not a fan of detecting charset since it will be additional overhead for every request. Maybe okay for PAC files but then again it's even easier to just override with an INI file setting like you said.

**Comment by SamuelePilleri** [comment]
Not for every request, just for the first one fetching the PAC file. Once it's fetched, decoded and compiled by the JS runtime it's enough.

**Comment by genotrance** [comment]
I'm adding `--pac_encoding` CLI option and `proxy:pac_encoding` into px.ini to handle this. Might not be easy for folks to know when to use this since Px will just crash or quickjs will complain about a bad PAC file. Probably need some more data to handle this gracefully and direct users to use this option when needed.

**Comment by genotrance** [comment]
This should be supported in v0.8.4. Added the `--pac_encoding` CLI flag and `proxy:pac_encoding` in px.ini.
