### ISSUE TITLE
px status command

### ISSUE THREAD

**Issue by noloader** [genotrance/px#171]
We are trying to use `px` in a corporate network. Something changed recently and `px` stopped working. We believe the change was some endpoint security tool mucking with firewall rules. In fact, several things broke including other tools like `scoop`.

We are trying to learn the status of `px`. We would like it to report its status, but there does not seem to be a way to do it. If there is a way, it is not documented in the README. For completeness, `--verbose` does not provide status messages.

Please provide a command to have `px` report its status. It can exit immediately after providing a status.

-----

Here is an example of what we are trying to troubleshoot. `px` does not provide any output, even with `--verbose`.

<img width="866" alt="px-startup" src="https://user-images.githubusercontent.com/3538226/192888840-207e12ba-2505-468a-9ace-d76dd8921fdb.png">

**Comment by genotrance** [comment]
How have you installed px - is it the Nuitka binary or pip installed? Also does `px -h` work?

**Comment by genotrance** [comment]
`--verbose` requires `--foreground` - I'll update Px to do that automatically. Regardless, the code needs some rework since it shouldn't be crashing.

**Comment by genotrance** [comment]
This should be fixed in v0.8.4 - `--verbose` now runs in the foreground.
