### ISSUE TITLE
Px related issues when other applocations make localhost request

### ISSUE THREAD

**Issue by mys2kor** [genotrance/px#172]
Hello,

I am facing issue when launching Bot Framework Composer with Px is running. The details including logs, and explanation is available in the issue I raised on BFC repository (link below).

https://github.com/microsoft/BotFramework-Composer/issues/9328#issuecomment-1268736076

I am having issues with other programs as well. I am hoping fixing this issue will help fix other issue has well. Can you please look into this? Thanks.

**Comment by genotrance** [comment]
Hello @mys2kor, I'm struggling to understand the context with Bot Framework Composer. It's not clear to me why headers and the body are interleaved. Px is just passing data through from the server back to the real client so if data is coming out of order, it is not going to know any better.

Can you please explain what's going on here? Or if there's a simpler example that is easy to reproduce, I'm happy to look deeper into this.

**Comment by mys2kor** [comment]
@genotrance I am not knowledgeable about the innner workings of Bot Framework Composer.
@ramfattah, @johnataylor, @tracyboehrer , would you guys be able to answer the question?

PS:- Bot Framework Composer is working fine with CNTLM proxy.

**Comment by genotrance** [comment]
Closing this issue - if you have a plain HTTP request, the response includes the headers followed by the body. I don't see why this has anything to do with Px - especially the comment about bridge() and how headers are returned inline. The client should be using the data sent back. Insufficient info to do anything further.
