### ISSUE TITLE
'Requires libcurl' when using 'tools.py --libcurl'

### ISSUE THREAD

**Issue by massimodt** [genotrance/px#175]
https://github.com/genotrance/px/blob/faaa57c2e7bd06f1bc502e8a1d63b6911a667c27/tools.py#L11

Hi,
the import of mcurl.py stops the execution before downloading the libcurl.dll

moreover, the link "https://curl.se/windows/curl-win%s-latest.zip" does not work anymore.

thank you.

**Comment by genotrance** [comment]
I'll fix this during the next Px release - thanks for reporting!
