### ISSUE TITLE
Little enhancement and bugfix

### ISSUE THREAD

**Issue by McBane87** [genotrance/px#18]
2 Bugfixes:
* In my environment, configparser does not know "default_section", not sure if it's in general like this. I disbaled this line via comment.
* When using "noproxy" and "get_destination" trys to resolv the ip address, I'm running into a timeout (exception) because of "handle_one_request". This behaviour makes px to timeout all internet requests, because my local DNS isn't able to resolv internet addresses. In my environment resolving internet addresses is done on proxy side. That's why I added an own expception there.

1 Enhancement:
* Added possibility to set "--listen", "--port" and "--config" via commandline/arguments

```patch
--- px.py	2018-01-17 17:14:16.692200100 +0100
+++ px.py	2018-01-17 17:20:24.890200100 +0100
@@ -495,7 +495,10 @@
 
             dprint(netloc)
             spl = netloc.split(":", 1)
-            addr = socket.getaddrinfo(spl[0], int(spl[1]))
+            try:
+		addr = socket.getaddrinfo(spl[0], int(spl[1]))
+            except:
+		addr = ""
             if len(addr) and len(addr[0]) == 5:
                 ipport = addr[0][4]
                 dprint("%s => %s + %s" % (self.path, ipport, path))
@@ -622,9 +625,13 @@
     global MAX_WORKERS
     global PORT
 
+    for i in range(len(sys.argv)):
+        if "--config=" in sys.argv[i]:
+            INI = sys.argv[i].split("=")[1]
+    
     if os.path.exists(INI):
         config = configparser.ConfigParser()
-        config.set(config.default_section, "allow", "*.*.*.*")
+        #config.set(config.default_section, "allow", "*.*.*.*")	//Produces Error
         config.read(INI)
 
         if "proxy" in config.sections():
@@ -689,6 +696,13 @@
             parsenoproxy(sys.argv[i].split("=")[1])
         elif "--allow=" in sys.argv[i]:
             parseallow(sys.argv[i].split("=")[1])
+        elif "--listen=" in sys.argv[i]:
+            LISTEN = sys.argv[i].split("=")[1]
+        elif "--port=" in sys.argv[i]:
+            try:
+		PORT = int((sys.argv[i].split("=")[1]))
+            except:
+		pass
 
     if "--gateway" in sys.argv:
         LISTEN = ''

```

**Comment by McBane87** [comment]
Additionally to the above patch, I implemented some other things. Maybe you like them:
* It's now possible to specify more than 1 parent proxy separated by comma. Px will iterate through them and picks the first, which is working. (This happens on every request. Maybe to much?)
* Added the possibility to override/append the "user-agent" string in the header

```patch
--- px.py	2018-01-17 17:20:24.890200100 +0100
+++ px.py	2018-01-18 12:28:03.479309000 +0100
@@ -1,4 +1,5 @@
 from __future__ import print_function
+from contextlib import closing
 
 import base64
 import multiprocessing
@@ -69,7 +70,9 @@
 NOPROXY = netaddr.IPSet([])
 ALLOW = netaddr.IPSet([])
 NTLM_PROXY = None
+NTLM_PROXIES = []
 PORT = 3128
+UA_OVERRIDE = None
 
 MAX_IDLE = 30
 MAX_DISCONNECT = 3
@@ -165,8 +168,33 @@
         #return socket.getfqdn(host)
         return host
 
+    def check_socket(self, host, port):
+        dprint("Checking for working connection on " + str(host) + ":" + str(port) + " ")
+	try:
+	    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as sock:
+	        sock.settimeout(0.25)
+	        if sock.connect_ex((str(host), int(port))) == 0:
+                    dprint("Connection successful for " + str(host) + ":" + str(port) + " ")
+		    return 1 # open port
+	        else:
+                    dprint("Connection failed for " + str(host) + ":" + str(port))
+		    return 0 # not open port
+	except:
+	     dprint("Connection failed with exception for " + str(host) + ":" + str(port) + " ")
+	     traceback.print_exc(file=sys.stdout)
+	     return 0 # failed, considered not open port
+    
     def do_socket(self, xheaders=[], destination=None):
-        dprint("Entering")
+        global NTLM_PROXY
+	
+	dprint("Finding working proxy")
+	for _proxy in NTLM_PROXIES:
+	    if (self.check_socket(host=_proxy[0], port=_proxy[1])) == 1:
+	        NTLM_PROXY = tuple(_proxy)
+		break
+	dprint("Using proxy: ", str(NTLM_PROXY[0]) + ":" + str(NTLM_PROXY[1]) + " ")
+	
+	dprint("Entering")
         if not destination:
             destination = NTLM_PROXY
 
@@ -187,10 +215,16 @@
         chk = False
         expect = False
         keepalive = False
+        ua = False
         cmdstr = ("%s %s %s\r\n" % (self.command, self.path, self.request_version)).encode("utf-8")
         self.client_socket.send(cmdstr)
         dprint(cmdstr)
         for header in self.headers:
+            if header.lower() == "user-agent":
+	        ua = True
+		if UA_OVERRIDE != None:
+		    self.headers[header] = UA_OVERRIDE
+	    
             h = ("%s: %s\r\n" % (header, self.headers[header])).encode("utf-8")
             self.client_socket.send(h)
             dprint("Sending %s" % h)
@@ -204,10 +238,13 @@
             elif header.lower() == "transfer-encoding" and self.headers[header].lower() == "chunked":
                 dprint("CHUNKED data")
                 chk = True
-
+	
         if not keepalive and self.request_version.lower() == "http/1.0":
             xheaders["Proxy-Connection"] = "keep-alive"
-
+		
+        if not ua and UA_OVERRIDE != None:
+            xheaders["User-Agent"] = UA_OVERRIDE
+	
         for header in xheaders:
             h = ("%s: %s\r\n" % (header, xheaders[header])).encode("utf-8")
             self.client_socket.send(h)
@@ -577,13 +614,20 @@
 
 def parseproxy(proxystr):
     global NTLM_PROXY
+    global NTLM_PROXIES
+    
+    proxysplit = [i.strip() for i in proxystr.split(",")]
 
-    NTLM_PROXY = proxystr.split(":")
-    if len(NTLM_PROXY) == 1:
-        NTLM_PROXY.append(80)
-    else:
-        NTLM_PROXY[1] = int(NTLM_PROXY[1])
-    NTLM_PROXY = tuple(NTLM_PROXY)
+    for proxystr in proxysplit:
+        _NTLM_PROXY = proxystr.split(":")
+        if len(_NTLM_PROXY) == 1:
+            _NTLM_PROXY.append(80)
+        else:
+            _NTLM_PROXY[1] = int(_NTLM_PROXY[1])
+        
+	if NTLM_PROXY == None:
+	    NTLM_PROXY = tuple(_NTLM_PROXY) # For Fallback, take the first only
+	NTLM_PROXIES.append(_NTLM_PROXY)
 
 def parseipranges(iprangesconfig):
     ipranges = netaddr.IPSet([])
@@ -624,6 +668,7 @@
     global MAX_IDLE
     global MAX_WORKERS
     global PORT
+    global UA_OVERRIDE
 
     for i in range(len(sys.argv)):
         if "--config=" in sys.argv[i]:
@@ -661,6 +706,11 @@
 
             if "noproxy" in config.options("proxy"):
                 parsenoproxy(config.get("proxy", "noproxy"))
+		
+            if "useragent" in config.options("proxy"):
+                useragent = config.get("proxy", "useragent")
+                if useragent:
+                    UA_OVERRIDE = useragent
 
         if "settings" in config.sections():
             if "workers" in config.options("settings"):
@@ -696,6 +746,8 @@
             parsenoproxy(sys.argv[i].split("=")[1])
         elif "--allow=" in sys.argv[i]:
             parseallow(sys.argv[i].split("=")[1])
+        elif "--useragent=" in sys.argv[i]:
+            UA_OVERRIDE = sys.argv[i].split("=")[1]
         elif "--listen=" in sys.argv[i]:
             LISTEN = sys.argv[i].split("=")[1]
         elif "--port=" in sys.argv[i]:

```

**Comment by genotrance** [comment]
Thank you for the contributions - I'll pull in the changes and post back here with an update.

**Comment by McBane87** [comment]
You're welcome. 
Please also add a "global INI" to "parsecli". I missed that in the patches above.

**Comment by genotrance** [comment]
Okay a question - why would you use noproxy when you cannot resolve any hostnames? Noproxy means Px has to directly talk to the host in question which means it needs to know the IP. Is this because you talk to such hosts in the noproxy list directly with IP addresses and not hostnames?

I've integrated the new CLI flags and useragent capability. Looking into the multi-proxy code now.

**Comment by genotrance** [comment]
I was looking at the multi-proxy enhancement and am wondering about your use case. How often is it the case that you have multiple proxies available, especially NTLM authenticating ones and that they could be down so you'd have to search for one that's up?

I was thinking more about a scenario where multiple proxy servers are available and Px would need to pick a random one to spread the load. But an admin would accomplish this by having multiple IPs for the same hostname since browsers would handle it just as well.

**Comment by McBane87** [comment]
Regarding the noproxy fix:
This fix not directly related to the no proxy logic. It's implemented because the "getaddrinfo" code gets only executed if the noproxy option is enabled. So if noproxy is enabled, the code tries to resolve all addresses (even addresses not related to noproxy) via my local dns, which isn't able to resolv internet addresses. And this leads into an exception.

Regarding multiple proxies:
Well in my environment the proxies are normally delivered via pac file. This pac file can chose from 10 proxies ( yes, we have 10 ntlm proxies :D ) and the client always gets two of them based on its source ip address. This is already the loadbalancing part. And the two proxies now known by the client are then the redundancy part. Which means, as long as proxy 1 is available, I should use proxy 1 and only if it's gone, proxy 2 should be asked.
So how am I doing this via PX-Proxy? Well, I've written a batch script, with the help of some other tools, which extracts the two proxies out of my pac file and then passes them to px proxy. And px is then doing the "take proxy 1 as long as it's available thing".

Regarding random proxy idea:
If you would make px, for example, to chose one out of two proxies randomly and then one proxy would not be available anymore. Many requests would fail randomly, because it maybe had chosen the wrong one for current request.

**Comment by genotrance** [comment]
I've integrated your getaddrinfo fix as well as multiple proxy support. cNTLM also uses them for failover rather than for load balancing so I have implemented it that way.

Please try it from source (or latest pre-release) and let me know your feedback.

By the way, issue #2 also requests PAC support, looks like it might help you as well.

**Comment by McBane87** [comment]
Thanks.
I've tested your latest code in my environment and so far it seems to work, after I fixed some things:
* made socktimeout able to be float (values less then 1 second are possible this way)
* fixed some issues regarding useragent option

``` patch
--- px.py       2018-02-22 16:19:50.051400100 +0100
+++ px.py       2018-02-22 16:24:29.915400100 +0100
@@ -160,7 +160,6 @@
     noproxy = netaddr.IPSet([])
     proxy_server = []
     stdout = None
-    useragent = ""
 
     ini = "px.ini"
     max_disconnect = 3
@@ -330,9 +329,9 @@
         dprint(cmdstr)
         for header in self.headers:
             hlower = header.lower()
-            if hlower == "user-agent" and State.useragent != "":
+            if hlower == "user-agent" and State.config.get("proxy", "useragent") != "":
                 ua = True
-                self.headers[header] = State.useragent
+                self.headers[header] = State.config.get("proxy", "useragent")
 
             h = ("%s: %s\r\n" % (header, self.headers[header])).encode("utf-8")
             self.client_socket.send(h)
@@ -351,8 +350,8 @@
         if not keepalive and self.request_version.lower() == "http/1.0":
             xheaders["Proxy-Connection"] = "keep-alive"
 
-        if not ua and State.useragent != "":
-            xheaders["User-Agent"] = State.useragent
+        if not ua and State.config.get("proxy", "useragent") != "":
+            xheaders["User-Agent"] = State.config.get("proxy", "useragent")
 
         for header in xheaders:
             h = ("%s: %s\r\n" % (header, xheaders[header])).encode("utf-8")
@@ -795,6 +794,21 @@
 
     State.config.set(section, name, str(val))
 
+def cfg_float_init(section, name, default, override=False):
+    val = default
+    if not override:
+        try:
+            val = State.config.get(section, name).strip()
+        except configparser.NoOptionError:
+            pass
+
+    try:
+        val = float(val)
+    except ValueError:
+        print("Invalid float value for " + section + ":" + name)
+
+    State.config.set(section, name, str(val))
+    
 def cfg_str_init(section, name, default, proc=None, override=False):
     val = default
     if not override:
@@ -860,7 +874,7 @@
 
     cfg_str_init("proxy", "noproxy", "", parsenoproxy)
 
-    cfg_str_init("proxy", "useragent", "", parsenoproxy)
+    cfg_str_init("proxy", "useragent", "")
 
     # [settings] section
     if "settings" not in State.config.sections():
@@ -869,7 +883,7 @@
     cfg_int_init("settings", "workers", "2")
     cfg_int_init("settings", "threads", "5")
     cfg_int_init("settings", "idle", "30")
-    cfg_int_init("settings", "socktimeout", "5")
+    cfg_float_init("settings", "socktimeout", "5.0")
 
     cfg_int_init("settings", "log", "0" if State.logger is None else "1")
     if State.config.get("settings", "log") == "1" and State.logger is None:
@@ -926,7 +940,7 @@
     if getattr(sys, "frozen", False) != False or "pythonw.exe" in sys.executable:
         detachConsole()
 
-    socket.setdefaulttimeout(State.config.getint("settings", "socktimeout"))
+    socket.setdefaulttimeout(State.config.getfloat("settings", "socktimeout"))
 
 ###
 # Exit related

**Comment by genotrance** [comment]
Thanks for checking the useragent piece - I wanted to use State.useragent since it will be faster than pulling the value from the config object when doing actual connections. I've made minor adjustments based on your patch and delivered an update which you could try out.

As for the socket timeout, if you see my implementation, I'm not checking the proxies on every connection separately - I'm actually failing over as part of the same connection. Hence, there's no separate timeout for checking versus connecting. Further, the way the failover works is as follows:-

Initial: proxies = [p1, p2, p3]
- Connect to proxies[0]
- If succeeds, keep connecting to proxies[0]
- If fails, proxies = [p2, p3, p1] and try again, [p3, p1, p2] and try again, [p1, p2, p3] ...
- Loop len(proxies) times before giving up

This way, I try the next proxy until I've tried all. Also, if a proxy fails, I only have to failover once and not on every connection. After p1 fails, I'm using p2 without checking p1 on every connection.

Lastly, what's the value of a float socket timeout? Setting it under a second is quite aggressive and will cause failover or connection failures unnecessarily. I don't mind adding it but honestly don't see the benefit.

**Comment by McBane87** [comment]
About UA:
Thanks. Looks like it's working now.

About the proxy failover:
Yes you are right. Didn't realized that. Great :-)

About timeout:
Well, most likely you are right about timouts less than 1 second, but I like the liberty to be able to use every value the underlying socket implementation is giving us. Also let's try to think into the other direction and assume someone wanting to use for example 2.25 seconds timeout. Would be great this person can use such value :-)

**Comment by genotrance** [comment]
Sounds fair - I've delivered your changes for --socktimeout.
