### ISSUE TITLE
Windows Defender "Threat Found" display

### ISSUE THREAD

**Issue by milyimi** [genotrance/px#186]
When I download "Px v0.8.4" and try to extract it, Windows Defender says "Threats found".

Target file name:
px-v0.8.4-windows.zip

**Comment by milicevica23** [comment]
I have the same problem

**Comment by ravikiranb36** [comment]
For me also showing same

**Comment by ravermeister** [comment]
Same here

**Comment by genotrance** [comment]
Please see [here](https://github.com/genotrance/px/issues/182#issuecomment-1574292664) for what I'm considering as the solution. Feedback appreciated.
