### ISSUE TITLE
keyring_jeepney broken

### ISSUE THREAD

**Issue by firefart** [genotrance/px#187]
Due to this https://github.com/jaraco/keyring/issues/646 `keyring_jeepney` is now not usable any more. You might want to mention this in the readme

**Comment by genotrance** [comment]
This is fixed in v0.9.0 still in development - see [branch](https://github.com/genotrance/px/tree/v090).

https://github.com/genotrance/px/issues/188#issuecomment-1826422011 for more details.

**Comment by genotrance** [comment]
[v0.9.0](https://github.com/genotrance/px/releases/tag/v0.9.0) has been released.
