### ISSUE TITLE
How to use PX with Windows 10

### ISSUE THREAD

**Issue by Dscheksn** [genotrance/px#19]
Hello,

can you explain in detail how to make PX work for Windows 10? I did the following:

Open px.ini and add my proxy under server=
Added allow = 127.0.0.1 + my own ip from ipconfig /all
Save px.ini
Run build.bat

I see a terminal for a blink of an eye and then it disappears. What am I doing wrong?

**Comment by genotrance** [comment]
If you already have Python setup, you just run ```python px.py```. If not, you can download the executable version from the [releases](https://github.com/genotrance/px/releases) page.

Building Px require Pyinstaller so it might not be working for you.

**Comment by sathiyasunsp** [comment]
i dont have python installed on my windows 2012 server, can i install and configure the px. I click on py application file(Failed to execute script px). Please advise.
