### ISSUE TITLE
Does this tool support Kerberos authentication to a corporate Web proxy ?

### ISSUE THREAD

**Issue by maaaaz** [genotrance/px#192]
Hello there,

Thank you for this great tool !
Does this tool, or could it, support Kerberos authentication to a corporate Web proxy (in situations where this proxy only accepts Kerberos authentication) ?

In order to, have, just like the [escobar](https://github.com/L11R/escobar/) tool, the possibility for the user, to send non-kerberized HTTP request to the Px listener, with that listener being authenticated through Kerberos on a Web proxy, in order for the HTTP request to go through the proxy ?

Cheers!

**Comment by genotrance** [comment]
Px supports every auth mechanism that curl supports including Kerberos. 

https://curl.se/libcurl/c/CURLOPT_HTTPAUTH.html

Kerberos is used first when you set auth to Negotiate.
