### ISSUE TITLE
Timeout and connection reset 

### ISSUE THREAD

**Issue by sdt1163** [genotrance/px#193]
I'm using px proxy to execute some terraform code. My px proxy is using a local PAC file which redirect URLs on 2 different proxy. One of them is a bluecoat using NTLM auth. It works pretty well, but sometimes we've got timeout, connection reset by peer when it's executed on linux RHEL. On Windows 10, we never have this deffect.
 On terraform output we've got some issues like bad MAC or tls timeout, this is like  px proxy cut the connection before the end of request. I can execute the same with curl, it will work most of time and randomly fails. If I use curl to authenticate directly on Blue Coat, I never have this issue.
 Are you aware of this issue ? I don't know how to highlight this issue, even in verbose mode there is not so much except the connection reset by peer which is not really true here.

**Comment by genotrance** [comment]
Can you see if this has anything to do with `--idle`? Default value in Px is 30 seconds which is the amount of time an HTTPS CONNECT is left idle before it is closed. I don't see why it should differ between Windows and Linux though.

Connection aborted is another old headache I'm yet to figure out as well. #152.

**Comment by genotrance** [comment]
Hope [v0.9.0](https://github.com/genotrance/px/releases/tag/v0.9.0) no longer has this issue.
