### ISSUE TITLE
px 0.9.0 - Windows: logging configuration inside px.ini file is ignored and no logging is produced

### ISSUE THREAD

**Issue by marcOcram** [genotrance/px#204]
Starting px with the log configuration entry does not produce any logging. It does not matter which value I use.

```ini
[proxy]
...

[settings]
log = 3
```

If I start px directly via cli `px.exe --uniqlog` a logging file is created

**Comment by genotrance** [comment]
Thanks for the report - will fix this in the next release. Until then, the config file won't work for setting `log` and env vars or cli flags will need to be used.

**Comment by genotrance** [comment]
Fixed in [v091](https://github.com/genotrance/px/tree/v091).

**Comment by genotrance** [comment]
[v0.9.1](https://github.com/genotrance/px/releases/tag/v0.9.1) has been released.
