### ISSUE TITLE
Thread safety of quickjs

### ISSUE THREAD

**Issue by llewellyn-marriott** [genotrance/px#206]
I have been having issues with PX crashing inconsistently, the logs wouldn't show much, until today when I noticed the following error:

```
MainProcess: Thread_33: 1707706381: /do_CONNECT/do_curl/select: 84b6c97c92f2a8d3c6adea7983b447d95e5cc656: Starting select loop
  File "C:\PX\PX-V08~1.4-W\http\server.py", line 421, in handle_one_request
  File "C:\PX\PX-V08~1.4-W\px\main.py", line 396, in do_CONNECT
  File "C:\PX\PX-V08~1.4-W\px\main.py", line 329, in do_curl
  File "C:\PX\PX-V08~1.4-W\px\main.py", line 403, in get_destination
  File "C:\PX\PX-V08~1.4-W\px\wproxy.py", line 467, in find_proxy_for_url
  File "C:\PX\PX-V08~1.4-W\px\wproxy.py", line 258, in find_proxy_for_url
  File "C:\PX\PX-V08~1.4-W\px\pac.py", line 71, in find_proxy_for_url
_quickjs.JSException: (Failed obtaining QuickJS error string. Concurrency issue?)
```

Note on the version number: I did try updating to 0.9 but still had intermittent crashes, with varying errors. I just don't have any of them saved.

I had a look through the code (I am not a Python dev) and from what I can see there is no state lock used when calling quickjs, which is shared between multiple threads.

In my px.ini file I set `threads = 1` and the intermittent crashes went away.

Looking at the quickjs Python package (https://pypi.org/project/quickjs/), it indicates that:

> QuickJS is currently thread-hostile, so this wrapper makes sure that all calls to the same JS runtime comes from the same thread.

Also, thank you for all your hard work on px, it has really been very useful for me.

**Comment by awl1** [comment]
Suffering from the same issue here - here is a screenshot of such a quickjs crash:

![quickjs_crash](https://github.com/genotrance/px/assets/11905025/77e2422c-7972-4684-9b20-1981ceefd4b8)

Reproducing is easy: Just use Eclipse IDE, configure px 0.9.0 (localhost:3128) as manual proxy and try to install any more complex plugin from the marketplace -> Eclipse tries to access px.exe from multiple threads, leading to the assertion failure...

I fully agree: Thank you for all your hard work on px, it has really been very useful for everybody here at my customer behind the NTLM/Kerberos proxy...

**Comment by genotrance** [comment]
Thank you for the report - I'll get this resolved in v0.9.1.

**Comment by genotrance** [comment]
Fixed in [v091](https://github.com/genotrance/px/tree/v091). Thank you for making it so easy @llewellyn-marriott!

> The quickjs Python library is thread-safe if Function is used. If the Context class is used directly, it can only ever be accessed by the same thread. This is true even if the accesses are not concurrent.

**Comment by genotrance** [comment]
[v0.9.1](https://github.com/genotrance/px/releases/tag/v0.9.1) has been released.

**Comment by mckirk** [comment]
> The quickjs Python library is thread-safe if Function is used. If the Context class is used directly, it can only ever be accessed by the same thread. This is true even if the accesses are not concurrent.

Sorry to resurrect a closed issue @genotrance, but reading this makes me wonder if the fix actually goes far enough. The quoted text seems to imply that a Context can only ever be accessed by the thread that created it, whereas the fix (as I understand it) only prevents concurrent accesses by different threads.

**Comment by genotrance** [comment]
> Sorry to resurrect a closed issue @genotrance, but reading this makes me wonder if the fix actually goes far enough. The quoted text seems to imply that a Context can only ever be accessed by the thread that created it, whereas the fix (as I understand it) only prevents concurrent accesses by different threads.

@mckirk - it may be good enough for regular Python with the GIL but perhaps not for the new free-threaded version in 3.13. Px does not yet support it though. I'll keep an eye out for any more crash reports in this area. Thanks for the info!

**Comment by genotrance** [comment]
@mckirk - Given the general cleanup of other PAC related functionality, I'm updating the code to use `quickjs.Function` instead of `Context`. Hopefully it will result in better performance and stability.
