### ISSUE TITLE
How to download latest release via script

### ISSUE THREAD

**Issue by vx-i** [genotrance/px#211]
I would like to automate the px installation via PowerShell script, but stuck on download url.

With help of tags I can use https://github.com/genotrance/px/releases/latest/ url. The problem are the file names itself. It should be something like px-latest-windows-amd64.zip.

Is there any trick how to do this?

**Comment by vx-i** [comment]
Found one :-)

$json_latest = Invoke-WebRequest -Uri https://api.github.com/repos/genotrance/px/releases/latest
$obj_latest = ConvertFrom-Json $json_latest
$px_version = $obj_latest.tag_name
Invoke-WebRequest -Uri https://github.com/genotrance/px/releases/latest/download/px-$px_version-windows-amd64.zip -OutFile px.zip
Invoke-WebRequest -Uri https://github.com/genotrance/px/releases/latest/download/px-$px_version-windows-amd64.zip.sha256 -OutFile px.zip.sha256

**Comment by genotrance** [comment]
Also worth mention that px is available with [scoop](https://scoop.sh/) in case you would like to use it. I use scoop for all my Windows apps.
