### ISSUE TITLE
sCHANNEL Native SSL for Px-Windows

### ISSUE THREAD

**Issue by delassio** [genotrance/px#219]
How i can switch to curl schannel support for px-windows version

is there a possibility to check ca used is schannel or openssl ?

https://curl.se/docs/sslcerts.html

Can you please add feature to use windows store to fix issue when proxy use ssl inspection ?

**Comment by genotrance** [comment]
Similar to #224.

You could also just replace the libcurl.dll with the one from [JuliaBinaryWrappers](https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases) project. Their Windows build uses schannel, unlike the curl.se/windows build which uses libressl. 

That's what [pymcurl](https://pypi.org/project/pymcurl) uses and what px will leverage in the next release.
