### ISSUE TITLE
Virus messages from windows binary

### ISSUE THREAD

**Issue by Klaas-** [genotrance/px#23]
Hi,
virustotal reports a few issues with the binaries:
https://www.virustotal.com/de/file/95f52cec423181d0c59fbc867f1b9709cb847589fed64edb172e86e85c2d090e/analysis/1518603360/

The major players don't seem to recognize anything so I guess it's false positive but you should look into that.

Greetings
Klaas

**Comment by genotrance** [comment]
Thank you for the feedback - I'm not sure what exactly to do with this since the site doesn't really make any recommendations on how to resolve this.

**Comment by Klaas-** [comment]
Okay, I'll assist :)
In general most antivirus companys have a webpage or e-mail to report false positives.
I have contacted:
* Baidu
* Cylance
* jiangmin
* trendmicro
* webroot

I can't find a contact for  Antiy-AVL  though

**Comment by genotrance** [comment]
Wow, thank you!

**Comment by genotrance** [comment]
In the name of addressing this issue somewhat, I'm removing the UPX compression step of the Px.exe binary. The benefits are marginal (compression of 100k in a 6.5MB binary) anyway.

**Comment by genotrance** [comment]
Just posted v0.3.0 without UPX compression.

**Comment by Klaas-** [comment]
https://www.virustotal.com/#/file/2d420edf6d72e17bb17e984477af200fce2d7a64b4cc69dca235db8b7a3e00b0/detection :) it does change the outcome a little :) I'll try to contact those companys aswell.
