### ISSUE TITLE
Newer Versions keep Console window open instead of starting background tasks

### ISSUE THREAD

**Issue by MrFly72** [genotrance/px#232]
I dont know at which release this changed, but older versions (eg. 0.8.3) start background task instead of keeping console window open.
Is there any switch that can force the old behaviour?
Background:
I usually recommend our developers to put PX into Autostart, so that when they start work everything is handy in place.
With newer releases the console window stays open and if they close it, PX will be gone.
If there is no switch to do this right now, it would come handy if there would be one in the future.
(Also in a px.ini configuration item)

**Comment by MrFly72** [comment]
Ok, I did a quick test and it was introduced in 0.9.0 with the new embedded Python.

**Comment by genotrance** [comment]
This was reported in https://github.com/genotrance/px/issues/203. The [readme](https://github.com/genotrance/px?tab=readme-ov-file#misc) has been updated to document how to get Px running without a console.

**Comment by genotrance** [comment]
Closing this issue since #203 has been reopened.
