### ISSUE TITLE
no connection to proxy after some times

### ISSUE THREAD

**Issue by neverset123** [genotrance/px#236]
is there any cache that px-proxy is using on ubuntu 22.04? after reboot for about 30 mins the px-proxy works perfectly, afterwards there is proxy connection problem. I have to reboot the machine, and then it works again. No clue what is causing the problem...
btw: previous I used ntlm, and it works perfectly without any problem.

**Comment by genotrance** [comment]
Can you run Px with logging enabled with `—debug`?

There’s no cache but px does remember the auth method for a proxy and if auth fails for any reason. Logs will help understand what’s going on.

**Comment by neverset123** [comment]
thanks for all replies! the issue was caused by kerberos ticket cache location in krb5.conf.
