### ISSUE TITLE
Add ability to run Px in foreground in frozen mode

### ISSUE THREAD

**Issue by genotrance** [genotrance/px#25]
Binary version of Px runs in the background already but a flag or config option should allow the script version to run in the background too. This will be useful if Px is run from source or installed via pip or other methods.

As a complement, the --quit flag should also be enhanced to work as expected in this mode.

**Comment by planesweep** [comment]
It would be great if you can add a config to start the px binary in the foreground. It would be easier to start and stop the px binary via bat or cmd.

**Comment by genotrance** [comment]
@planesweep, I'm updating this issue to your request. While it won't behave like a standard executable (since px.exe is a GUI application and doesn't really have a console), it can be accomplished by redirecting all output to the console (if it exists) instead of just during startup. Basically, don't call detachConsole() until exit.

The original issue can be accomplished by running Px with pythonw.exe which runs scripts in the background. I'll need a separate issue to fix the --quit flag in script mode since it quits any python or pythonw process instead of just px.

**Comment by genotrance** [comment]
Added the --foreground flag and config setting to run Px in the foreground.

**Comment by genotrance** [comment]
`pythonw -m px --foreground` no longer seems to work - tested Python 3.13. The `--foreground` flag only exists for Nuitka, Pyinstaller or other frozen builds but none are officially supported anymore. Code remains in place for now.
