### ISSUE TITLE
"px --quit" does not terminate the executable 

### ISSUE THREAD

**Issue by planesweep** [genotrance/px#27]
**steps to reproduce**
* start the px executable directly in Windows 7
* enter px --quit in cmd
* Px is not running

**expected behaviour**
* start the px executable directly in Windows 7
* enter px --quit in cmd
* Px is terminated

**Nevertheless, thank you very much for sharing this AWESOME tool!**

**Comment by genotrance** [comment]
Thank you for your feedback. Please check out the latest build to see if it fixes your issue.

**Comment by planesweep** [comment]
Hi,
thank you very much. "px --quit" is working now, well done.

Cheers
Gregor

**Comment by genotrance** [comment]
Thanks for checking and your feedback. :thumbsup:
