### ISSUE TITLE
pywin32 issue in Python 3.6 fixed?

### ISSUE THREAD

**Issue by McBane87** [genotrance/px#28]
I'm not sure howto exactly reproduce the error mentioned in https://github.com/genotrance/px/issues/9 , but using the newest pywin32 from https://github.com/mhammond/pywin32 isn't causing any exceptions or errors so far in my environment.

EDIT: 
OK, just saw you dropped pywin32 support at all. Well then, this isn't interesting anymore :-)

**Comment by genotrance** [comment]
Ya, it's likely pywin32 fixed this already but I couldn't get it to work generically for Kerberos and NTLM. Also, don't see a value in two code paths to do the same thing. It's harder to test and sustain.

**Comment by genotrance** [comment]
I've brought back pywin32 for NTLM based on the info here. The winkerberos module isn't 100% with NTLM auth so best to go with what works.
