### ISSUE TITLE
Failed to execute script px

### ISSUE THREAD

**Issue by n0211541** [genotrance/px#31]
Hello,  I opened the px.ini in notepad++ with admin rights and entered my server info.  When I try to run px.exe, i am getting Failed to execute script px.  My co-worker, however was able to complete the same steps with no issue.

Are there any troubleshooting steps I can take?

Thank you,
Teresa

**Comment by genotrance** [comment]
Can you please run with the ```--debug``` flag or set ```log = 1``` in px.ini? It will generate log files with some details hopefully.

Can you also let me know which OS version you are using and the version of Px?

**Comment by renepauli** [comment]
Same problem here. I get this error sometimes after reboot with autostart configured.

**Comment by genotrance** [comment]
Thanks for the info. Can you please try the command line version of px.exe from [here](https://transfer.sh/U99f9/px.exe) and let me know what happens when you run it with --debug?

`px.exe --debug`

**Comment by renepauli** [comment]
Problem is I only get this error if I reboot/boot my machine (if autostart is configured). And this only happend sometimes not always. If I start px.exe manually I have no issues.

**Comment by genotrance** [comment]
I have reproduced this problem and am looking into what's happening. Thanks for the report.

**Comment by genotrance** [comment]
This has been fixed in the latest release.

**Comment by sathiyasunsp** [comment]
How can i install and configure the px on our windows 2012 server. Note:- Dont have python already installed. Please give a simple notes from download -->install-->Configuration.
