### ISSUE TITLE
build.bat does not work anymore

### ISSUE THREAD

**Issue by ccbur** [genotrance/px#33]
Executing build.bat in HEAD gives me:

`
Unable to find "c:\Miniconda\Lib\site-packages\tld\res\effective_tld_names.dat.txt" when adding binary and data files.
`

And no px.exe is generated. 

When I remove this dependency to miniconda, build.bat works as expected.

Is this file really needed?

**Comment by genotrance** [comment]
Ya this file was a dependency for pypac. However, I'm removing the pypac dependency altogether since it is very heavy in RAM usage - upto 14 times more than without. I'll be checking in my changes after some additional testing.

**Comment by genotrance** [comment]
Fixed in the latest build - removed the pypac dependency.
