### ISSUE TITLE
Exception happened during reading response code

### ISSUE THREAD

**Issue by Vefty** [genotrance/px#38]
[debug-Process-2.log](https://github.com/genotrance/px/files/1805464/debug-Process-2.log)

Px started manuallу with admin rights.
After the first connect attempt I **always** get the exception "list index out of range":

_Exception happened during processing of request from ('127.0.0.1', 55607)
Traceback (most recent call last):
  File "socketserver.py", line 639, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "socketserver.py", line 696, in __init__
  File "http\server.py", line 418, in handle
  File "px.py", line 288, in handle_one_request
  File "http\server.py", line 406, in handle_one_request
  File "px.py", line 677, in do_CONNECT
  File "px.py", line 563, in do_transaction
  File "px.py", line 416, in do_socket
IndexError: list index out of range_

The second attempt is **always** ok.

**Comment by genotrance** [comment]
I've added code to handle the exception, will push shortly. It's not clear to me what exactly is being returned though so you will still see a "Bad request" entry in the log but it will show what was actually returned and that will help understand what the actual issue is.

**Comment by Vefty** [comment]
A bit different log with a new assembly. 
[debug-Process-2.log](https://github.com/genotrance/px/files/1828925/debug-Process-2.log)

**Comment by genotrance** [comment]
Just posted a fixed build. Thanks for checking.

**Comment by Vefty** [comment]
Thank you, no more exceptions. I can just see a bad response from a proxy.
Just in case the log attached.
[debug-MainProcess.log](https://github.com/genotrance/px/files/1831927/debug-MainProcess.log)

**Comment by genotrance** [comment]
Looks like the proxy is saying "Connection: close" instead of "Proxy-Connection: close" so Px thinks the connection should still be usable. I can add a change to handle this so that Px doesn't assume the connection is still available.

**Comment by genotrance** [comment]
I just posted a fix for this - you should no longer see the bad response in your logs.

**Comment by Vefty** [comment]
Thank you, I don't see any errors anymore.
