### ISSUE TITLE
Add ftp support

### ISSUE THREAD

**Issue by McBane87** [genotrance/px#39]
In "get_destination" please add ftp like this:

``` python
if not port:
    if parse.scheme == "http":
        port = 80
    elif parse.scheme == "https":
        port = 443
    elif parse.scheme == "ftp":
        port = 21
```

**Comment by genotrance** [comment]
I just tried through the parent proxy and you get back an html listing. However, Px has no idea how to talk to an FTP server in pass-through mode. Will the above change be good enough?

**Comment by McBane87** [comment]
For me, this solution was good enough to make my FTP request work. Without this I ran into an exception, because there was a port missing on later functions.

**Comment by genotrance** [comment]
Okay, I've checked in your change. I'll keep this open until I figure out what to do in pass-through or noproxy mode.

**Comment by koconder** [comment]
@genotrance and @McBane87 you might as well map them all?

> [urlparse documentation](https://docs.python.org/2/library/urlparse.html): The module has been designed to match the Internet RFC on Relative Uniform Resource Locators. It supports the following URL schemes: file, ftp, gopher, hdl, http, https, imap, mailto, mms, news, nntp, prospero, rsync, rtsp, rtspu, sftp, shttp, sip, sips, snews, svn, svn+ssh, telnet, wais.

**Comment by genotrance** [comment]
Closing this for now - if it becomes material or someone can contribute the changes, we can reopen as needed.
