### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by GregoryOtt** [genotrance/px#4]
Can you add a license to this repo because "no license" means strong copyright. My company has strong OSS policies that prevent me to use your tool.
Please, see this article from Github for more info: [https://choosealicense.com/no-license/](https://choosealicense.com/no-license/)

**Comment by genotrance** [comment]
Wow, I thought I had done this already :)

I'll set this as MIT so that it's as liberal as possible.

**Comment by genotrance** [comment]
Done, checked in the file.

**Comment by GregoryOtt** [comment]
Thanks for your great work on this tool!
