### ISSUE TITLE
Installation through setup.py requires README.txt file

### ISSUE THREAD

**Issue by zupan** [genotrance/px#44]
During the installation, following the instructions from README
```
# download master
python setup.py install
```
the installation breaks as it requires README.txt file which is not included in the repository.

When replacing both  occurrences of the `README.txt` with `README.md` in the `setup.py` file, the installation was successful.

If this is the intended use, I can create the pull request.

**Comment by geekonthepc** [comment]
+1

**Comment by genotrance** [comment]
Thanks for reporting, I've pushed a fix.
