### ISSUE TITLE
Provide a complete example px.ini with the binary distribution

### ISSUE THREAD

**Issue by jarrodhroberson** [genotrance/px#45]
please consider providing a complete `px.ini` file that gets output when running the binary download with all the options either commented out or set to their defaults. As it is now you have to guess at what the format should be.

**Comment by jarrodhroberson** [comment]
You can close this, I just figured out that the `--save` command line option does this.

Maybe make that more obvious or do it automatically the first time it runs.

**Comment by genotrance** [comment]
I was about to reply with `--save`. I mention it in the `Configuration` section of the readme. I don't default generate it since you could always just use it from the command line and never want an extra file.
