### ISSUE TITLE
Please enhance documentation regarding --install

### ISSUE THREAD

**Issue by DrVanScott** [genotrance/px#46]
Hi,

I wonder how Px is configured if it has been installed using "--install". Does it use the CLI parameters which have been specified together with --install or is Px expecting a config file in a certain location?

Can you please describe that in the README?

Great tool, anyway!

**Comment by DrVanScott** [comment]
And where does Px expect the configuration? User home? Folder containing px.exe?

**Comment by genotrance** [comment]
Px looks for px.ini at the same folder as the executable. When you use --save, it saves the config in this same location.

You can change the config file location with --config but if you run --install, it expects that default location.

**Comment by genotrance** [comment]
This has been updated in the README.

**Comment by DrVanScott** [comment]
Your commit defenitly helped , but unfortunately I am still not clear about that:

- I have installed px in C:\Program Files\px\
- open cmd
- cd "C:\Program Files\px"
- px --proxy=someproxy --save
- PX is telling me, that it has 

> Saved config to C:\Program Files\px\px.ini

- But there is no such file in that folder. Instead of this, it created/updated a file in %APP_DATA%\Local\VirtualStore\Program Files\px\px.ini

I also used "--install" to register automatic startup of px. As i cannot find any persistened config elsewhere on my system, i assume the automatically started instance of px is also using the file %APP_DATA%\Local\VirtualStore\Program Files\px\px.ini ?
