### ISSUE TITLE
winhttp_find_proxy_for_url: WinHttpOpen failed: 87

### ISSUE THREAD

**Issue by w1sht0l1v3** [genotrance/px#49]
Hi, is there something wrong i'm doing or it's not working?
![image](https://user-images.githubusercontent.com/1199041/39567570-18fcbd2c-4ec8-11e8-9dd3-9a5a74a94fae.png)

Below my config:
```
[proxy]
#server =
port = 3128
listen = 127.0.0.1
allow = *.*.*.*
gateway = 0
hostonly = 0
#noproxy = 127.0.0.1
#useragent = 

[settings]
workers = 2
threads = 5
idle = 30
socktimeout = 5.0
proxyreload = 60
foreground = 0
log = 1
```

And IE settings:
![image](https://user-images.githubusercontent.com/1199041/39567904-2386af54-4ec9-11e8-9a9f-1b79a9e31a72.png)

**Comment by SantoshSrinivas79** [comment]
Having the same issue but the binary from the releases page works just fine!! Running Windows 10

**Comment by SantoshSrinivas79** [comment]
https://github.com/genotrance/px/issues/43#issuecomment-387634858 fixes the issue for me. (Win 10 64 bit)

**Comment by genotrance** [comment]
@SantoshSrinivas79 - thank you for verifying, I'll close #43 shortly.
