### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by wiz21b** [genotrance/px#5]
Got this error : 

```
Traceback (most recent call last):
  File "px.py", line 606, in <module>
    runpool()
  File "px.py", line 451, in runpool
    httpd = ThreadedTCPServer((GATEWAY, PORT), Proxy)
  File "c:\PORT-STC\opt\python3\lib\socketserver.py", line 430, in __init__
    self.server_bind()
  File "c:\PORT-STC\opt\python3\lib\socketserver.py", line 444, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

I'd say it's because I'm not Administrator my my PC but I'm not sure...

I run in a corporate environment and I have set up the px.ini file correctly (I hope!). The error shows up right at the start of px execution.

**Comment by wiz21b** [comment]
Forget avout it, cntlm proxy was already running (and took over the socket/port) :-(

**Comment by genotrance** [comment]
I guess it could do with a nicer error message :)

**Comment by genotrance** [comment]
I've improved the error message in v0.2.1. Thanks for your feedback.

**Comment by domOrielton** [comment]
Not sure if it is something incorrect I have done but I'm still getting the following error in debug-MainProcess.log when px is trying to use a port that is already in use (port was still set to the standard 3128).

[WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

I ran netstat -ban  and could see the port was being used by spoolsv
 [spoolsv.exe]   TCP    10.171.42.80:3128      10.171.30.40:59606     ESTABLISHED

Changed the port in px.ini and everything worked again just fine - only mentioning this in case the improved error message you mentioned has been lost in some other change.

Thanks for a very useful program :)

**Comment by genotrance** [comment]
Can you please share the log or full stack trace? Will help identify where this is coming from.

**Comment by genotrance** [comment]
Looks like I was only printing the exception message and not a clean message - fixed this for real :)
