### ISSUE TITLE
winkerberos.GSSError: SSPI: InitializeSecurityContext: The token supplied to the function is invalid

### ISSUE THREAD

**Issue by glaukon-ariston** [genotrance/px#50]
I get the following error for both ca5d1fb and 26a98ba builds:

Process-1: MainThread: 1526291786: attach_console: Attaching to console 3684
Process-1: MainThread: 1526291786: parse_proxy: [('wwsgwy', 8080)]
Serving at 127.0.0.1:3128 proc Process-1
Process-1: MainThread: 1526291786: parse_config: proxy:server = wwsgwy:8080
Process-1: MainThread: 1526291786: parse_config: proxy:listen = 127.0.0.1
Process-1: MainThread: 1526291786: parse_config: proxy:port = 3128
Process-1: MainThread: 1526291786: parse_config: proxy:gateway = 0
Process-1: MainThread: 1526291786: parse_config: proxy:allow = *.*.*.*
Process-1: MainThread: 1526291786: parse_config: proxy:noproxy = 
Process-1: MainThread: 1526291786: parse_config: proxy:useragent = 
Process-1: MainThread: 1526291786: parse_config: proxy:hostonly = 0
Process-1: MainThread: 1526291786: parse_config: settings:workers = 2
Process-1: MainThread: 1526291786: parse_config: settings:threads = 5
Process-1: MainThread: 1526291786: parse_config: settings:idle = 30
Process-1: MainThread: 1526291786: parse_config: settings:log = 0
Process-1: MainThread: 1526291786: parse_config: settings:socktimeout = 5.0
Process-1: MainThread: 1526291786: parse_config: settings:proxyreload = 60
Process-1: MainThread: 1526291786: parse_config: settings:foreground = 1
Process-1: MainThread: 1526291809: verify_request: Client address: 127.0.0.1
Process-1: Thread_0: 1526291809: do_GET: Entering
Process-1: Thread_0: 1526291809: do_GET: Path = http://hackage.haskell.org/package/ghcid-0.6.6.tar.gz
Process-1: Thread_0: 1526291809: do_transaction: Entering
Process-1: Thread_0: 1526291809: get_destination: hackage.haskell.org:80
Process-1: Thread_0: 1526291809: do_socket_connect: New connection: ('wwsgwy', 8080)
Process-1: Thread_0: 1526291809: do_proxy_type: Searching proxy type
Process-1: Thread_0: 1526291809: do_socket: Entering
Process-1: Thread_0: 1526291809: do_socket: GET http://hackage.haskell.org/package/ghcid-0.6.6.tar.gz HTTP/1.1
Process-1: Thread_0: 1526291809: do_socket: Sending User-Agent: cabal-install/1.24.0.0 (windows; i386)
Process-1: Thread_0: 1526291809: do_socket: Sending Host: hackage.haskell.org
Process-1: Thread_0: 1526291809: do_socket: Reading response code
Process-1: Thread_0: 1526291809: do_socket: Response code: 407 False
Process-1: Thread_0: 1526291809: do_socket: Reading response headers
Process-1: Thread_0: 1526291809: do_socket: Received Date: Mon, 14 May 2018 09:56:58 GMT
Process-1: Thread_0: 1526291809: do_socket: Received Content-Type: text/html
Process-1: Thread_0: 1526291809: do_socket: Received Cache-Control: no-cache
Process-1: Thread_0: 1526291809: do_socket: Received Content-Length: 3806
Process-1: Thread_0: 1526291809: do_socket: Received Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1526291809: do_socket: Received Proxy-Authenticate: sanitized (4)
Process-1: Thread_0: 1526291809: do_socket: Received Proxy-Authenticate: sanitized (27)
Process-1: Thread_0: 1526291809: do_socket: Reading response data
Process-1: Thread_0: 1526291809: do_socket: Content length 3806
Process-1: Thread_0: 1526291809: do_proxy_type: Auth mechanisms: NTLM Basic realm="MWG NTLM Auth" 
Process-1: Thread_0: 1526291809: do_proxy_type: Selected: {('wwsgwy', 8080): 'NTLM'}
Process-1: Thread_0: 1526291809: get_response: winkerberos SSPI
Process-1: Thread_0: 1526291809: do_socket: Entering
Process-1: Thread_0: 1526291809: do_socket: GET http://hackage.haskell.org/package/ghcid-0.6.6.tar.gz HTTP/1.1
Process-1: Thread_0: 1526291809: do_socket: Sending User-Agent: cabal-install/1.24.0.0 (windows; i386)
Process-1: Thread_0: 1526291809: do_socket: Sending Host: hackage.haskell.org
Process-1: Thread_0: 1526291809: do_socket: Sending extra Proxy-Authorization: sanitized len(77)
Process-1: Thread_0: 1526291809: do_socket: Reading response code
Process-1: Thread_0: 1526291809: do_socket: Response code: 407 False
Process-1: Thread_0: 1526291809: do_socket: Reading response headers
Process-1: Thread_0: 1526291809: do_socket: Received Date: Mon, 14 May 2018 09:56:59 GMT
Process-1: Thread_0: 1526291809: do_socket: Received Content-Type: text/html
Process-1: Thread_0: 1526291809: do_socket: Received Cache-Control: no-cache
Process-1: Thread_0: 1526291809: do_socket: Received Content-Length: 0
Process-1: Thread_0: 1526291809: do_socket: Received Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1526291809: do_socket: Received Proxy-Authenticate: sanitized (69)
Process-1: Thread_0: 1526291809: do_socket: Reading response data
Process-1: Thread_0: 1526291809: do_transaction: Auth required
Process-1: Thread_0: 1526291809: do_transaction: Challenged
Process-1: Thread_0: 1526291809: get_response: winkerberos SSPI
Traceback (most recent call last):
  File "px.py", line 272, in get_response
winkerberos.GSSError: SSPI: InitializeSecurityContext: The token supplied to the function is invalid

Process-1: Thread_0: 1526291809: do_transaction: Bad NTLM response
Process-1: Thread_0: 1526291809: do_GET: Error 503
Process-1: Thread_0: 1526291809: log_message: code 503, message Service Unavailable
Process-1: Thread_0: 1526291809: log_message: "GET http://hackage.haskell.org/package/ghcid-0.6.6.tar.gz HTTP/1.1" 503 -
Process-1: Thread_0: 1526291809: do_GET: Done

**Comment by genotrance** [comment]
This should be fixed with #34, please verify the latest build to see if it works for you.
