### ISSUE TITLE
Px not running on startup because the wrong command is being added to windows registry

### ISSUE THREAD

**Issue by victoraraujo01** [genotrance/px#57]
After noticing that px was not running on startup I checked the registry and found that the following command was added:

`c:\users\current_user\appdata\local\programs\python\python37-32\python.exe "C:\Users\current_user\AppData\Local\Programs\Python\Python37-32\Scripts\px"`

This command, however, fails when executed because the `px` file is an executable (not a script). It probably should be executed with the following command: 

`C:\Users\current_user\AppData\Local\Programs\Python\Python37-32\Scripts\px`

I installed Px using pip and Python 3.7 on a Windows 7 machine.

**Comment by genotrance** [comment]
Looks like a different use case from pure `python px.py` and `px.exe`. Installing from pip does create a shim so I'll have to see how to identify that and add that command instead.

**Comment by genotrance** [comment]
This has been fixed in #head, I'll mark it fixed once I post a new release on pip.

**Comment by genotrance** [comment]
v0.4.0 has been posted.
