### ISSUE TITLE
Some question about using this px

### ISSUE THREAD

**Issue by lvfanqie** [genotrance/px#59]
1. when I start to run px.py, will run continuously to authenticate with proxy server?
2. does it mean if I run any other script which can skip the proxy authentication if px.py is running on background?

**Comment by genotrance** [comment]
Yes, Px runs in the background as a proxy service until you tell it to exit. You can point the other script to connect to Px using standard proxy mechanisms to skip the NTLM authentication.

Can you explain your use case a bit more?

**Comment by lvfanqie** [comment]
Thanks for your reply. our company has a proxy server running on NTLM
scheme. and I am running a script which require to access http website.
This script lack of authentication handshake part.

if i want to call px in my script to authenticat with server, how could I
do it?

**Comment by genotrance** [comment]
Px is an HTTP proxy so you would use an HTTP library like `requests`, `urllib` or `libcurl`. You would use their API to point to Px as the proxy server to use.

So basically run Px on server pointing to the upstream proxy server and then point your script to Px at http://127.0.0.1:3128.

**Comment by lvfanqie** [comment]
I see. So for the configuration, let say the upstream proxy server is testproxy.com @ port 80, in the px.ini, I will set server = testproxy.com:80.
Question about IP interface, if my pc NIC ip=192.168..10.10, should I set the listen = 192.168.10.10, how about port? should I set it same as upstream proxy server, which is 80?

**Comment by genotrance** [comment]
Best to run Px on localhost assuming you want only connections from your local system to be accepted. If you run on the NIC interface, it will allow anyone on that network to connect which is probably not what you want.

**Comment by lvfanqie** [comment]
So in Px, localhost will route the message to NIC interface?

**Comment by genotrance** [comment]
Px will talk to the upstream proxy like any other application. It will only listen for connections on the localhost so only programs running on the same system can talk to it.

**Comment by lvfanqie** [comment]
got you. Thank you! i will try this on our system to see how that works.
