### ISSUE TITLE
Symantec heuristics  blocks latest 0.4.0 px.exe :(

### ISSUE THREAD

**Issue by s-kocher** [genotrance/px#62]
My company using Symantec Enpoint Protection that blocked the latest px.exe (https://github.com/genotrance/px/releases/download/v0.4.0/px.exe) as soon it was downloaded.

Confirmation on virus total that 3 antivirus actors are more paranoid than others : https://www.virustotal.com/fr/file/93b54b5b6154c536f7ec0a85ed90ea25aa5ed66c7f61d2acbc37cab8a9231440/analysis/

I can understand that fresh unknown and unsigned executable acting as a proxy can trigger some heuristic based on suspect behaviors (ml.xxxx is obviously for machine learning and behavior analysis to detect new unsigned virus) but anybody know how to interact with Symantec and make them reasonable quickly ?

May be a question of time, previous release is ok : https://www.virustotal.com/fr/file/a57048602c634fdcf3ac9df8ba4c3e81856606ce5ea0dc156a33f6538e2c7574/analysis/
Was it similar for previous releases ?

**Comment by s-kocher** [comment]
I answered myself : I saw similar issue with previous releases : https://github.com/genotrance/px/issues/23

I just submitted the false report for symantec : https://submit.symantec.com/false_positive/

Probably all releases will be like that :(

**Comment by genotrance** [comment]
Thank you for following up on this.
