### ISSUE TITLE
Running as a service through 'serman' does not function

### ISSUE THREAD

**Issue by Geordi7** [genotrance/px#63]
I am trying to use px.exe on a windows server. I have put all the configuration options in px.ini.

Running it as a logged in user works fine. In procexp64 I see three instances - the worker, the parent, and the grandparent - the parent has an open socket listening on the right port.

I installed px.exe as a service using serman (a project on github). It does not function though.

I see in procexp64 that there are only two instances running, neither has an open socket.

I can't tell if px is reading its configuration successfully, I checked the running directory and the executable directory, both contain my px.ini. There is no output in the serman log files.

**Comment by genotrance** [comment]
Can you share your app.xml file so that I can try this out?

**Comment by Geordi7** [comment]
Contents of px-serman-config.xml:
```
<service>
  <id>PX</id>
  <name>PX Proxy Helper</name>
  <description>This service allows http(s) proxy punchthrough for local processes at http://localhost:3128</description>
  <executable>c:\Program Files (x86)\PX Proxy Helper\px.exe</executable>
  <logmode>rotate</logmode>
</service>
```

**Comment by Geordi7** [comment]
Please note I am running the latest 'release' version: v0.3.0

I will try v0.4.0 as well...

**Comment by genotrance** [comment]
How do you specify the user and pass for the service? Sorry I've not used serman before.

**Comment by Geordi7** [comment]
Firstly, with v0.4.0 it WORKS!

As for serman, that config file was sufficient for me to install the service, so I'm not sure how to answer the question.

On windows server editions you can open the Services tool and edit the owning user in the properties of the service.

**Comment by genotrance** [comment]
Ya I was curious if you could specify the user info with serman but it will be better to use the Services tool.

**Comment by mantsurovr** [comment]
Hello there!
If you don't mind let me left serman config working for me:
```xml
<service>
  <id>PX</id>
  <name>PX</name>
  <description>Small transparent local http(s) proxy server working with local processes at http://localhost:3128</description>
  <executable>c:\opt\px\px.exe</executable>
  <workingdirectory>c:\opt\px\</workingdirectory>
  <arguments>--config c:\opt\px\px.ini</arguments>
  <logmode>rotate</logmode>
  <onfailure action="restart" delay="5 sec"/>
  <onfailure action="restart" delay="5 sec"/>
  <onfailure action="restart" delay="5 sec"/>
  <serviceaccount>
    <domain>.</domain>
    <user>administrator</user>
    <password>password</password>
  </serviceaccount>
</service>
```
Service PX works through serman with administrtator user account, and I used workingdirectory and arguments directives.
