### ISSUE TITLE
[feature request] Add socks support

### ISSUE THREAD

**Issue by xliiv** [genotrance/px#69]
See: https://en.wikipedia.org/wiki/SOCKS#Protocol

**Comment by genotrance** [comment]
I'm not sure I quite understand. Px is an http proxy that handles NTLM auth for clients that don't whereas SOCKS is a general purpose proxy that can handle any protocol but doesn't have anything to do with http or NTLM.

Can you please explain your use case, might make more sense that way.

**Comment by xliiv** [comment]
It looks like i need to do some reading then :)
Feel free to close it.

**Comment by genotrance** [comment]
Okay, let me know.
