### ISSUE TITLE
command window stays open

### ISSUE THREAD

**Issue by jpvlerbe** [genotrance/px#72]
Hi

Thank you for this wonderful project, that solved a lot of my issues.

I configured PX to run at boot by running px --install. However, now the command window opens (and stays open) after boot. If you close the window the proxy server is also shut down. Is there a way to run px without keeping the CMD window open?

In the case that you get it working without the CMD window open, how can you shutdown px then? For instance in the case you are working at another location not behind a proxy.

**Comment by genotrance** [comment]
Glad px is useful :)

How did you install px?

**Comment by jpvlerbe** [comment]
If I remember correctly, I have installed through pip. However I have been using it for a while already, so I am not that sure.

**Comment by genotrance** [comment]
Do you see the popup even if you run px after logging in? Can you check the version of px with px --help? What version of Python are you using?

**Comment by genotrance** [comment]
You can always exit px with `px --quit` if it is running in the background.

Meanwhile, I checked and for some reason I've configured pip to run px in the console using `console_scripts` instead of `gui_scripts`. I'm not sure why I did this but I suspect there was some issue with the shim that pip creates. I'll check and let you know if this can be changed.

**Comment by jpvlerbe** [comment]
Any news on this?

**Comment by JasonRoesbeke** [comment]
Would like to also have it running in the background
@genotrance any update on this?

**Comment by moritzrupp** [comment]
This is still not working. If you install px with `pip` or `python setup.py install`, the command windows will stay  open. Only if you directly use the provided `px.exe` file it is working as expected.

**Comment by Loriden** [comment]
I'm also experiencing this issue - installed via PIP. If i can provide any more detail to help resolve, please ask. 

Px v0.4.0
pip 19.2.1 from c:\python37\lib\site-packages\pip (python 3.7)

**Comment by Postlagerkarte** [comment]
Any news on this? Having the same issue.  /cc @genotrance 

Version: 0.4.0 installed via pip on windows 10

**Comment by datadu-de** [comment]
would like to get rid of the cmd-window as well  👍

**Comment by crumpetcrusher** [comment]
running from pip or just px.py will leave the command window up, same for when you install it to start at boot

to run the latest code, clone the repo and compile it to .exe as shown in the travis.yml file:

https://github.com/genotrance/px/blob/master/.travis.yml#L38-L44
* install dependencies
* compile px.py
* run pyinstall to build exe

drop that in a folder of your choosing and run the config/install to have it start in the background properly.
