### ISSUE TITLE
403 - Request forbidden -- authorization will not help  when using Px as proxy

### ISSUE THREAD

**Issue by rsau** [genotrance/px#74]
I have found that on some sites Px output following message. 

`$ curl --proxy 127.0.0.1:3128 is.gd`  
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 403</p>
        <p>Message: Forbidden.</p>
        <p>Error code explanation: 403 - Request forbidden -- authorization will not help.</p>
    </body>
</html>
```
To make sure that it is not something in my system settings, I tried another tool/proxy [Fiddler](https://www.telerik.com/fiddler)  which is listening on `127.0.0.1:8888`  

When I run   
`$ curl --proxy 127.0.0.1:8888 is.gd`   

```html
<html>                                             
<head><title>301 Moved Permanently</title></head>  
<body bgcolor="white">                             
<center><h1>301 Moved Permanently</h1></center>    
<hr><center>nginx/1.4.6 (Ubuntu)</center>          
</body>                                            
</html>                                            

```
It makes sense as I haven't enabled `--location ` option. 

my .curlrc  

```
user-agent "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3607.0 Safari/537.36"
``` 

It doesn't matter what is in my .curlrc file. I have tried different user agent including empty curlrc file. 
result is always same with Px.   
Same thing is happening with drupal.org  

`$ curl --proxy 127.0.0.1:3128 drupal.org`   

I am running Px v0.4.0 on Windows 2012. 
I have tried curl from git-bash and Cygwin with same results. 
It is not only with curl command though. 
[Insomnia](https://insomnia.rest/)  and [Postman](https://www.getpostman.com/)  have exact same behavior when I switch proxies.   

 Let me know if more information is needed.  

**Edit:**   I have just tested with Cntlm and it is working fine. Only Px has above issue.

**Comment by genotrance** [comment]
Can you please enable debug and post the logs generated? It might give some useful clues.

**Comment by rsau** [comment]
Hi 

I have started using Fiddler as default but I'll post debug log asap.

**Comment by genotrance** [comment]
Please reopen when you have some more info.
