### ISSUE TITLE
Higher CPU Load of PX Windows Process

### ISSUE THREAD

**Issue by JAAdrian** [genotrance/px#76]
Hi all,

I have successfully installed and configure PX and it runs like a charm. 
Nevertheless, I experience a constant, rather high CPU load of 13% of the PX process on Windows while idling.
Is this by design or can this also be reduced somehow? Can I provide any useful information?

---

Windows 7, 64 Bit
Company Proxy Firewall

---

**Comment by JAAdrian** [comment]
Nevermind, this issue is currently only occurring very randomly and is not easy to reproduce. You can close this issue

**Comment by genotrance** [comment]
Sounds good.
