### ISSUE TITLE
Secure problem

### ISSUE THREAD

**Issue by gregor21** [genotrance/px#77]
Hi,

I try to work with PX but I have problem. When I run Firefox and go to any page I got message: "Your connection is not secure". 

What can I do with that?

**Comment by genotrance** [comment]
Can you please provide some details on how you have configured Px and Firefox and which website you are trying to go to? Logs will also help.

**Comment by gregor21** [comment]
Windows 10x64
Version px-v0.4.0 from zip, unpacked and:
px --proxy=myproxy.mydomain.com:8080 --save
px --install

In firefox set to 127.0.0.1:3128 for all protocols (checked)
I try to go on https://google.pl and other
What's the best.... In another computer with windows 7x64 with exactly the same PX configuration and firefox - it works

How can I make logs?

**Comment by genotrance** [comment]
Sounds like a cert issue not related to Px, can you try directly or using another proxy?

You can get logs with the --debug flag.

**Comment by gregor21** [comment]
Thanks for your replay. I tried directly and there is still problem. So you are right - it it not related to Px. The computer is in company's network in domain etc. First, I will try to solve the basic problem....

**Comment by genotrance** [comment]
I suspect it is probably because of some TLS version issue. Hope you figure it out.
