### ISSUE TITLE
can't install the px on my win2012 server.

### ISSUE THREAD

**Issue by sathiyasunsp** [genotrance/px#84]
How can i install and configure the px on our windows 2012 server. Note:- Dont have python already installed. Please give a simple notes from download -->install-->Configuration.
I already download the px latest version once i extract the file in server then changed the server/port then tried to execute the py but was getting(failed to execute script px).

**Comment by sathiyasunsp** [comment]
was trying to install via pip but was getting the connection timed out.
C:\Users\A>pip install px
Collecting px
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x000000FE378D2198>, 'Connection to pypi.org
timed out. (connect timeout=15)')': /simple/px/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x000000FE378C2DD8>, 'Connection to pypi.org
timed out. (connect timeout=15)')': /simple/px/

**Comment by ihmels** [comment]
You could just download the binary from the [releases page](https://github.com/genotrance/px/releases).

**Comment by genotrance** [comment]
Seems like you tried pip and the script directly. I agree, trying the exe might be worth a try.

The script has a bunch of dependencies which are described in the README so you might want to check that your Python install has all those things.
