### ISSUE TITLE
auth priority order - should it be in the order the Server specifies?

### ISSUE THREAD

**Issue by btsimonh** [genotrance/px#88]
@genotrance -
please have a look at 
https://github.com/btsimonh/px/pull/2/commits

I read somewhere that the order of auth schemes in the server's Proxy-Authenticate header(s) determines the server's preferences, so changed the search for auth to be based on the order in the servers headers.
The PR is currently against my own master branch, but if you think this is a useful addition, then feel free to incorporate.  Did not want to throw another PR at you if it's not appropriate....

**Comment by genotrance** [comment]
Your commit looks like the right fix. I've incorporated it in https://github.com/genotrance/px/commit/d196d2ad66e3b3ee84b429f54c7bb283562389c0. It is the same as issue 2 in #71 and PR #83.

**Comment by btsimonh** [comment]
I've scanned the commit, and everything looks sweet :)  thankyou!
