### ISSUE TITLE
Socket error: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by rubin55** [genotrance/px#89]
I'm behind a "McAfee Web Gateway" NTLM proxy. Small GETs seem to go fine, but anything more substantial seems to stall. bellow log output is from a standard px config, verified working by `curl --proxy http://10.10.10.1:3128` https://start.duckduck.go.com/`.

The below occurs at a random moment during the session (I might download 4kb, I might download 5mb, I rarely if ever download the entire file, which in this case is 9.8mb). Curl command used is: `curl --proxy http://10.10.10.1:3128 http://mirror.scalabledns.com/centos/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-devel-1.8.0.212.b04-0.el7_6.x86_64.rpm --output test.rpm`. Note that other mirrors/sites give the same results. Log output:

```
MainProcess: Thread_4: 1562596863: fwd_resp: Entering
MainProcess: Thread_4: 1562596863: log_message: "GET http://mirror.scalabledns.com/centos/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-devel-1.8.0.212.b04-0.el7_6.x86_64.rpm HTTP/1.1" 200 -
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Date: Mon, 08 Jul 2019 14:40:57 GMT
MainProcess: Thread_4: 1562596863: fwd_resp: Returning ETag: "5cb9d6cf-9d1bf8"
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Server: nginx/1.14.2
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Content-Type: application/x-redhat-package-manager
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Accept-Ranges: bytes
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Cache-Control: no-cache
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Last-Modified: Fri, 19 Apr 2019 14:10:23 GMT
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Content-Length: 10296312
MainProcess: Thread_4: 1562596863: fwd_resp: Returning Proxy-Connection: Keep-Alive
MainProcess: Thread_4: 1562596863: fwd_data: Reading response data
MainProcess: Thread_4: 1562596863: fwd_data: Content length 10296312
MainProcess: Thread_0: 1562596872: handle_one_request: Socket error: [WinError 10053] An established connection was aborted by the software in your host machine
MainProcess: Thread_0: 1562596872: handle_one_request: Host disconnected
MainProcess: Thread_0: 1562596872: handle_one_request: Socket error: [WinError 10053] An established connection was aborted by the software in your host machine
MainProcess: Thread_0: 1562596872: handle_one_request: Host disconnected: 2
MainProcess: Thread_0: 1562596872: handle_one_request: Socket error: [WinError 10053] An established connection was aborted by the software in your host machine
MainProcess: Thread_0: 1562596872: handle_one_request: Host disconnected: 3
MainProcess: Thread_0: 1562596872: handle_one_request: Socket error: [WinError 10053] An established connection was aborted by the software in your host machine
MainProcess: Thread_0: 1562596872: handle_one_request: Closed connection to avoid infinite loop
```

I'm not sure what "WinError 10053" or "the software in your host machine" signifies, but I would love to understand what happens and fix this if possible.

**Comment by rubin55** [comment]
This might be the cause and/or related: https://bugs.python.org/issue27682

**Comment by genotrance** [comment]
I guess it is worth asking what version of Python is being used here. Do you still see the issue with another version of Python?

**Comment by rubin55** [comment]
I couldn't try with python 3.7.4rc2 because of #90 . The problem occured with the downloaded / released latest version of px.exe.

**Comment by genotrance** [comment]
Can you run curl with -v to see what's going on?

[This](https://github.com/genotrance/px/commit/1aa88058faf17d58c06f5c736220cdb224c95d00) commit fixed the issue around larger files - curl would wait for a while and then give up since nothing was being sent by px, which was busy downloading everything into memory before sending anything back to curl.

**Comment by rubin55** [comment]
Is that commit in one of the released binaries?

**Comment by genotrance** [comment]
It's been there for almost a year now.

**Comment by rubin55** [comment]
It turns out the issue I've been running into is a feature called “Data Trickling” in McAfee Web Gateway (a proxy server implementation that also does content scanning and what not based on heuristics). It's  documented here: https://community.mcafee.com/t5/Documents/Web-Gateway-Understanding-Progress-Indication-Methods/ta-p/553861

From the above documentation: _“Data Trickling can work for any client device or software that downloads data. It is an alternative to Progress Pages, but does not provide any particular visual progress indication beyond that provided by the web browser or client software itself. Data Trickling, from the point of view of an end-user, will make downloads appear very slow. Therefore, we recommend Progress Pages always be enabled and Data Trickling enabled as a fallback for clients that cannot use Progress Pages (this is exactly how the default rule sets are configured).

Data Trickling effectively throttles the download connection speed between the Web Gateway and the client, sending only a tiny amount of data that prevents the TCP connection from timing out. When the Gateway finishes scanning the file for viruses and malware (finding none), the remaining portion of the file is sent to the client at full network speed.

Because estimations of download time are provided by the web browser, and it is not aware of what the Web Gateway is doing, estimated download times will initially look extremely long to a user. The image below shows download progress indication provided by Internet Explorer v8 while Data Trickling is occurring.”_

The behaviour from the `px` point of view is download suddenly slowing down to 1 byte per second for multiple minutes (observed 3 to 9 minutes so far). In my case, it was the client that cancelled the connection - Reason: automatic mirror switching when a download is below X speed for Y amount of time. The WinError messages are a proxy client (in my case yum from centos within a docker build) aborting the connection because it is horrified by the 1 byte per second transfer speed for more than 30 seconds. In a vain attempt to get better speeds, it switches to another mirror where the problem of course remains because it's the proxy causing it, not the specific mirror (of which the client has no way of knowing).

I think this can be closed, but I hope the above explanation might show up on a couple of internet searches when people have strange / extreme latencies when using px in combination with MWG!

**Comment by genotrance** [comment]
This is very interesting! I don't think Progress Pages is applicable for our use case so Data Trickling it is.

I think the reason it breaks on http is because px is waiting for 4096 bytes [at a time](https://github.com/genotrance/px/blob/master/px.py#L988) before sending it back to the client. After the first 4096, getting only 1 byte per 1000 might keep px's connection open with the gateway but nothing will be sent back to the client which probably times out. Or like you are saying, client might ditch the connection altogether cause it is too slow.

I'm curious if the failure occurs on https as well since we are using [select](https://github.com/genotrance/px/blob/master/px.py#L900) and I am wondering if that 1 byte does make it back to the client.

**Comment by rubin55** [comment]
I tested this with both `http` and `https`. I noticed that MWG apparently cannot do (or at least in this particular configuration doesn't) man-in-the-middle style https termination (like bluecoats do for example). What I think that means is, that if I download over an https link, the MWG cannot inspect the payload and just passes it along. I.e, it does not hold the stream/file for inspection, no Data Trickling occurs, download finishes normally. When I download from the exact same host using http, I immediately get the data trickling behaviour.

Downloads with progress stuck at either 0% or 50ish% for 3 minutes, then immediately finish:
```
# curl --proxy localhost:3128 http://mirror.us-midwest-1.nexcess.net/CentOS/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-devel-1.8.0.212.b04-0.el7_6.x86_64.rpm --output test.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.8M  100  9.8M    0     0  69102      0  0:02:29  0:02:29 --:--:-- 2760k
```

Downloads normally, due to usage of https. Note the same URL as above except for scheme:
```
# curl --proxy localhost:3128 https://mirror.us-midwest-1.nexcess.net/CentOS/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-devel-1.8.0.212.b04-0.el7_6.x86_64.rpm --output test.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.8M  100  9.8M    0     0  2513k      0  0:00:04  0:00:04 --:--:-- 2465k
```

**Comment by genotrance** [comment]
Px has now switched to relying on libcurl to deal with the proxy, hopefully it can handle this situation better.
