### ISSUE TITLE
Year 30828 out of range

### ISSUE THREAD

**Issue by jinder** [genotrance/px#9]
Hi,

I've used pyinstaller to build px on Windows 7, using Python 3.6,  I'm getting the following error while trying to connect to the proxy:  ValueError year 3083 is out of range in sspi.py line 111.

![image](https://cloud.githubusercontent.com/assets/1503474/26829232/a10f8548-4abc-11e7-8f91-243b16612b67.png)

Any ideas?

**Comment by jinder** [comment]
Looks like it might be caused by this:  https://sourceforge.net/p/pywin32/bugs/748/

Will try downgrading to Python 3.5

**Comment by jinder** [comment]
Have confirmed that it's the bug linked above.  Downgrading to Python 3.5 has fixed my issue, so will close.

**Comment by rasgg** [comment]
Shouldn't we keep this open until it's fixed upstream?

**Comment by stolpovsky** [comment]
Please consider changing to 'open' until fixed.

**Comment by jinder** [comment]
Reopened

**Comment by genotrance** [comment]
Looks like this could be fixed if Px switches to winkerberos, per the link to the pywin32 issue. I'm not sure if it's worth the effort but open to suggestions.

**Comment by snovik75** [comment]
I confirm the issue. Is there another workaround apart from downgrading python?

**Comment by genotrance** [comment]
Just for kicks, I tried this with Python 3.6.1 and 3.6.2. I tried with pywin32 v220 as well as v221 and it's still broken. The fix is required within win32security.pyd which is C code and not easy to work around.

**Comment by genotrance** [comment]
Thanks to help from the [winkerberos](https://github.com/mongodb-labs/winkerberos/) team, Px works with winkerberos so Python 3.6+ is now supported.

pywin32 SSPI is still supported so if winkerberos isn't available, Px will fall back to pywin32 as long as the Python version is < 3.6.

**Comment by genotrance** [comment]
Given Px now works around this issue by using winkerberos, I propose marking this as fixed. Feedback appreciated.

**Comment by genotrance** [comment]
So I had to bring back pywin32 for NTLM auth since winkerberos was failing for some NTLM use cases. Some folks may still run into this issue. The recommendation is to upgrade your Python to the latest version since a fix is in place.

**Comment by lvfanqie** [comment]
@genotrance I still got this issue with latest px code. My python is 36-64. How could i fix it?

**Comment by genotrance** [comment]
Is it possible to update your Python to latest version somehow? Also install latest version of pywin32?

**Comment by genotrance** [comment]
I know it is broken on 3.6.1 and 3.6.2. I haven't tried 3.6.3 but I'm currently running 3.6.4 and don't see the issue anymore.

**Comment by lvfanqie** [comment]
I checked my python version , it's 3.6.6. Is there any way to fix it?

**Comment by lvfanqie** [comment]
I found this issue happens more when there's multi clients connected through proxy.

**Comment by genotrance** [comment]
What version of pywin32 do you have installed? I have 222. Also is your Python 32-bit or 64-bit? Miniconda or Python.org?

**Comment by lvfanqie** [comment]
pywin32=223, python is 3.6.6-64 bit from python.org

**Comment by lvfanqie** [comment]
@genotrance any suggestion?

**Comment by genotrance** [comment]
@lvfanqie: can you check if [this issue](https://github.com/mhammond/pywin32/issues/748) helps? Looks like older version of 220 was also present in the path.

**Comment by lvfanqie** [comment]
@genotrance my win32api version is '223'. How could I check pywintype version?  I got following errors:
>>> import pywintypes
>>> fixed_file_info = win32api.GetFileVersionInfo(pywintypes.__file__, '\\')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (1813, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The specified resource type cannot be found in the image file.')

**Comment by genotrance** [comment]
I tried and no idea :(

Another option is to `pip remove pywin32` and then reinstall and see if it helps any. I don't have a 64-bit Python setup so unsure if this is broken or an install issue.

**Comment by lvfanqie** [comment]
unfortunately, I tried reinstall the pywin32 but still get the same issue.
