### ISSUE TITLE
Forward requests when proxy turned off

### ISSUE THREAD

**Issue by groupmsl** [genotrance/px#91]
When I'm at work, I have to enable the proxy on my laptop in order to access the internet. Out of the office I need to turn it off. I've set environment variables for all my command line applications to use Px (http_proxy=localhost:3128 and https_proxy), but when the proxy is off this doesn't work. Is there a way to get Px to simply forward requests when the proxy is off?

I've tried --noproxy=* but this doesn't seem to work.

I'd sooner not have to change my environment every time I leave the office if possible.

Thanks!

**Comment by genotrance** [comment]
When you say "proxy is off" - what do you mean? Do you go into Internet Options and disable the checkbox?

If there is no proxy info to read from Internet Options, px should be defaulting to direct after [this](https://github.com/genotrance/px/pull/80) PR.

**Comment by groupmsl** [comment]
Yes, that is exactly what I mean - disabled in internet options.

If I run px after this is done it prints "No proxy server or noproxy list defined" to the console.

I then try and perform a "git clone" (or similar) and get "fatal: unable to access 'https://github.com/genotrance/px.git/': Received HTTP code 501 from proxy after CONNECT"

Even though the proxy is off, I still have "http_proxy" and "https_prxy" environment variables set, pointing to px. Obviously if I remove them everything works fine, but I then have to restore them next time I turn the proxy on.

Am I doing something wrong?

**Comment by groupmsl** [comment]
I tried this again after your comment, and I'm not sure what I'm doing differently now, but this seems to be working. Sorry for wasting any time - thanks!
