### ISSUE TITLE
Px detected as virus by Microsoft Defender

### ISSUE THREAD

**Issue by rubin55** [genotrance/px#92]
Latest px binary from releases, I get the following:

![Capture](https://user-images.githubusercontent.com/6214491/60967813-8d1bcd80-a2e9-11e9-9595-ec853df8c6ad.PNG)

**Comment by rubin55** [comment]
Output from Virus Total (seems to me to be mostly heuristic checks that cause this, not sure though):
![Capture](https://user-images.githubusercontent.com/6214491/60968211-8772b780-a2ea-11e9-991a-b070f5c0c34e.PNG)

**Comment by DennisGaida** [comment]
... and blocked by **Windows SmartScreen** filter. I had to manually unblock the px.exe file by right clicking it > Properties > This file came from another computer and might be blocked [...] > Unblock.

**Comment by Klaas-** [comment]
You can try to contact microsoft (and other AV engines), I've done so in the past but many do not care ...
https://github.com/genotrance/px/issues/23

**Comment by DennisGaida** [comment]
I have submitted the current px.exe to Office 365 Advanced Threat Protection as a false positive. The Windows Defender page to report false positives seems down right now: https://www.microsoft.com/en-us/wdsi/filesubmission

In any case the px.exe file could be made a lot less suspicious by adding a bit of metadata - authorship information, version and in the best case some kind of certificate. I believe this could be done with a manifest file. Maybe there is also another packer than pyinstaller?

**Comment by mungojam** [comment]
VirusTotal does show some odd things on latest release:

https://www.virustotal.com/gui/file/a63c3104a1a2a2d80e2b9bbfd4b06d90877e7a257e96c716965d1ecedba1ec91/behavior/VenusEye%20Sandbox

![image](https://user-images.githubusercontent.com/3154635/80102533-c799e280-856a-11ea-9ebb-401b44c175a5.png)

**Comment by DennisGaida** [comment]
The *latest* release is from 2018 (0.4.0). I downloaded the latest px.exe and uploaded to Virustotal and did not get any result like you showed: https://www.virustotal.com/gui/file/93b54b5b6154c536f7ec0a85ed90ea25aa5ed66c7f61d2acbc37cab8a9231440/behavior/Tencent%20HABO

Do explain how you got your results and what you tried. Also the px.exe is only flagged by 5 vendors as suspicious, most vendors do not flag px.exe.

Dropping mssrv.exe sounds weird and I don't think px.exe did that.

**Comment by mungojam** [comment]
I used the release after that: (https://github.com/genotrance/px/releases/tag/vHEAD)

I just repeated the test and it shows the same thing (same link as above):

https://www.virustotal.com/gui/file/a63c3104a1a2a2d80e2b9bbfd4b06d90877e7a257e96c716965d1ecedba1ec91/behavior

**Comment by DennisGaida** [comment]
@mungojam seems to only be in the *VenusEye Sandbox*. Check the other sandboxes, no mssrv.exe "dropped" or any file like that created.

**Comment by genotrance** [comment]
Binary releases have been problematic and efforts on px has been minimal so releases are lagging and infrequent.

I'm moving towards a source only release model so this won't be fixed or relevant going forward.

Similar to #106.

**Comment by genotrance** [comment]
Note that binary builds are back - see https://github.com/genotrance/px/issues/130#issuecomment-1075307879. It is now built with Nuitka so hopefully we see fewer such issues.
