### ISSUE TITLE
px process not starting.

### ISSUE THREAD

**Issue by sathiyasunsp** [genotrance/px#94]
After the python/px installation configured the px.ini then tried to start the px(px --start) but its not starting and it just goes hung without and return code.

Also, Please let me know what would be the service name once its started running in windows.

E:\px-master>px --install
Px already installed

Below is the start command issued but no reply for ever.
E:\px-master>px --start
Serving at 127.0.0.1:443 proc MainProcess
Serving at 127.0.0.1:443 proc Process-1

Once I Killed the command then I ran px --quit below was the return message.
E:\px-master>px --quit
Px is not running

Below is our px.ini config file. Please advise if everything looking good? 

[proxy]
server = 10.xxx.xx.70:xx80
pac = 
port = 443
listen = 127.0.0.1
allow = *.*.*.*
gateway = 0
hostonly = 0
noproxy = 
useragent = 
username = accounts\new_proxy_user
auth = 

[settings]
workers = 2
threads = 5
idle = 30
socktimeout = 20.0
proxyreload = 60
foreground = 0
log = 0

**Comment by moritzrupp** [comment]
This could be related to #72. If you install px with `pip` or `python setup.py install`, the command windows will still open. After you execute `px` it is actually running and not hung. As soon as you killed the command, px is no longer running, hence the `px --quit` says no px is not running.

Try download the provided `px.exe` file in the releases. This is working as expected.
