### ISSUE TITLE
New release + conda packaging

### ISSUE THREAD

**Issue by fcollonval** [genotrance/px#95]
Hey @genotrance, thx for this awesome tool. I submit a [PR to create a conda package](https://github.com/conda-forge/staged-recipes/pull/9181) for `px`.
Would you like to be one of the maintainer (i.e. you will be prompt with notifications when a update needs to be carried out)?

The recipe is based on git tags. Do you plan to do a new release with the latest change soon?

**Comment by genotrance** [comment]
Thanks you for creating the package! I don't mind being notified, sure.

It's about time I released 0.5.0 and kick off another pre-release cycle.

**Comment by fcollonval** [comment]
`px-proxy` is now on conda-forge 🎉 
Recipe repository (if you want to get the badges have a look at the README): https://github.com/conda-forge/px-proxy-feedstock
package should soon appears on conda-forge

**Comment by genotrance** [comment]
Hello @fcollonval - Px now depends on libcurl and while the Linux build expects libcurl to be installed by the package manager, the Windows version carries a copy of the dll in the release binaries I post on Github and on Pypi. How do we update the conda recipe to include this for Windows?

Thanks for your help in advance.

**Comment by fcollonval** [comment]
Hey @genotrance 

`libcurl` is available as [conda package](https://anaconda.org/conda-forge/libcurl). I did not keep with the latest version. But typically you need to update the [meta.yaml](https://github.com/conda-forge/px-proxy-feedstock/blob/main/recipe/meta.yaml). You will need to add `libcurl` to the `requirements.run` list. And to build for windows, you will need to remove the `skip: true` in the `build` section.
